Repository codesquad-members-2022/sidedish, pull requests merged in 2022-04, with the labels that each got.

#45 [team-13] Inu & Alan - styled component 및 헤더
  .gitignore
  README.md
  backend/README.md
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/categories.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/components/GnbMenu.js
  frontend/src/components/Header.js
  frontend/src/index.js
  frontend/src/styles/global.js
  frontend/src/styles/theme.js
Labels: review-FE

#20 [Team-03][BE] 쿠킴 & 루이 - 데이터베이스 설계, Mock API Server, 배포 아키텍처, 프로젝트 세팅
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/sidedish/com/ComApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/sidedish/com/ComApplicationTests.java
  README.md
Labels: review-BE

#6 [team-32][FE][otter & jinnie] header, nav 기본적인 컴포넌트 구성
  .gitignore
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/kr/codesquad/sidedish/SidedishApplication.java
  be/src/main/resources/application.properties
  be/src/test/java/kr/codesquad/sidedish/SidedishApplicationTests.java
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/App.css
  fe/src/App.js
  fe/src/component/Header/Header.css
  fe/src/component/Header/Header.js
  fe/src/component/Tab/List.js
  fe/src/component/Tab/Tab.css
  fe/src/component/Tab/Tab.js
  fe/src/component/UI/Card.css
  fe/src/component/UI/Card.js
  fe/src/index.css
  fe/src/index.js
  fe/src/reset.css
Labels: review-FE

#48 [Team-5 FE BB & JinJeon] Sidedish 프로젝트 1주차(수요일) 코드 리뷰 요청
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/sidedish/SidedishApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/sidedish/SidedishApplicationTests.java
  README.md
  fe/.gitignore
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/robots.txt
  fe/src/App.jsx
  fe/src/Component/Header/Header.jsx
  fe/src/Component/Main/Main.jsx
  fe/src/Styles/Normalize.js
  fe/src/Styles/Reset.js
  fe/src/index.jsx
Labels: review-FE

#21 [team-06][BE] - 1주차 1차 PR
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/sidedish/SidedishApplication.java
  be/src/main/resources/application.properties
  be/src/test/java/sidedish/SidedishApplicationTest.java
Labels: review-BE

#51 [team-11] 1주차 1번째 PR Nick + J
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/Components/header/GNB.jsx
  src/Components/header/ListItem.jsx
  src/Components/header/main.jsx
  src/GlobalStyles.js
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: review-FE

#12 [Team34][BE] sidedish 프로젝트 생성 및 도메인, DTO 작성
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/team34/sidedish/SideDishApplication.java
  BE/src/main/java/com/team34/sidedish/domain/Category.java
  BE/src/main/java/com/team34/sidedish/domain/CategoryDish.java
  BE/src/main/java/com/team34/sidedish/domain/Dish.java
  BE/src/main/java/com/team34/sidedish/domain/DishImage.java
  BE/src/main/java/com/team34/sidedish/domain/Member.java
  BE/src/main/java/com/team34/sidedish/domain/Order.java
  BE/src/main/java/com/team34/sidedish/dto/CategoriesResponse.java
  BE/src/main/java/com/team34/sidedish/dto/CategoryResponse.java
  BE/src/main/java/com/team34/sidedish/dto/ItemDetailResponse.java
  BE/src/main/java/com/team34/sidedish/dto/ItemResponse.java
  BE/src/main/java/com/team34/sidedish/dto/ItemsResponse.java
  BE/src/main/java/com/team34/sidedish/dto/OrderRequest.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/team34/sidedish/SidedishApplicationTests.java
Labels: review-BE

#23 [team15] iOS - bibi, 푸코 / 메인 뷰와 상세 뷰 만들기 (진행 중)
  .gitignore
  README.md
  sidedishApp/.swiftlint.yml
  sidedishApp/Podfile
  sidedishApp/Podfile.lock
  sidedishApp/sidedishApp.xcodeproj/project.pbxproj
  sidedishApp/sidedishApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  sidedishApp/sidedishApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sidedishApp/sidedishApp.xcodeproj/project.xcworkspace/xcuserdata/bibi.xcuserdatad/UserInterfaceState.xcuserstate
  sidedishApp/sidedishApp.xcodeproj/xcuserdata/bibi.xcuserdatad/xcschemes/xcschememanagement.plist
  sidedishApp/sidedishApp.xcworkspace/contents.xcworkspacedata
  sidedishApp/sidedishApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sidedishApp/sidedishApp/AppDelegate.swift
  sidedishApp/sidedishApp/Assets.xcassets/AccentColor.colorset/Contents.json
  sidedishApp/sidedishApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  sidedishApp/sidedishApp/Assets.xcassets/Contents.json
  sidedishApp/sidedishApp/Base.lproj/LaunchScreen.storyboard
  sidedishApp/sidedishApp/Base.lproj/Main.storyboard
  sidedishApp/sidedishApp/CardFactory.swift
  sidedishApp/sidedishApp/DetailViewController.swift
  sidedishApp/sidedishApp/FirstSectionViewController.swift
  sidedishApp/sidedishApp/Info.plist
  sidedishApp/sidedishApp/MainViewCardCell.swift
  sidedishApp/sidedishApp/MainViewController.swift
  sidedishApp/sidedishApp/MainViewHeader.swift
  sidedishApp/sidedishApp/SFProDisplay-Regular.OTF
  sidedishApp/sidedishApp/SceneDelegate.swift
  sidedishApp/sidedishApp/SecondSectionViewController.swift
  sidedishApp/sidedishApp/ThirdSectionViewController.swift
  sidedishApp/sidedishApp/model/Badge.swift
  sidedishApp/sidedishApp/model/MainCard.swift
Labels: review-iOS

#53 [Team-07] [FE] [ver & S] 첫번째 PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/default-template.md
  BE/Readme.md
  FE/.gitignore
  FE/Readme.md
  FE/babel.config.js
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.js
  FE/src/App.scss
  FE/src/components/Header/Header.js
  FE/src/components/Header/Header.scss
  FE/src/image/cart.svg
  FE/src/image/logo.svg
  FE/src/image/logo1.svg
  FE/src/image/myPage.svg
  FE/src/image/search.svg
  FE/src/index.js
  FE/src/scss/_reset.scss
  FE/webpack.config.js
  README.md
Labels: review-FE

#29 [team-33 sonya & 난정] 1주차 수요일 PR
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  backend/.keep
  frontend/sidedish/.gitignore
  frontend/sidedish/README.md
  frontend/sidedish/package-lock.json
  frontend/sidedish/package.json
  frontend/sidedish/public/index.html
  frontend/sidedish/public/reset.css
  frontend/sidedish/public/sidedish.json
  frontend/sidedish/src/App.css
  frontend/sidedish/src/App.js
  frontend/sidedish/src/BigSidedish.css
  frontend/sidedish/src/BigSidedish.js
  frontend/sidedish/src/Header.css
  frontend/sidedish/src/Header.js
  frontend/sidedish/src/index.css
  frontend/sidedish/src/index.js
Labels: review-FE

#28 [Team-16][iOS] 메뉴 목록 CollectionView 구현
  .gitignore
  README.md
  SideDishApp/.swiftlint.yml
  SideDishApp/DetailDishInfo.swift
  SideDishApp/OrderingCollectionViewDataSource.swift
  SideDishApp/OrderingCollectionViewDelegate.swift
  SideDishApp/Podfile
  SideDishApp/Podfile.lock
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SideDishApp/SideDishApp.xcodeproj/xcshareddata/xcschemes/SideDishApp.xcscheme
  SideDishApp/SideDishApp.xcworkspace/contents.xcworkspacedata
  SideDishApp/SideDishApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SideDishApp/SideDishApp/Controller/DetailViewController.swift
  SideDishApp/SideDishApp/Controller/OrderingViewController.swift
  SideDishApp/SideDishApp/EndPoint.swift
  SideDishApp/SideDishApp/HTTPMethod.swift
  SideDishApp/SideDishApp/Info.plist
  SideDishApp/SideDishApp/NetworkError.swift
  SideDishApp/SideDishApp/NetworkManager.swift
  SideDishApp/SideDishApp/SupportingFiles/AppDelegate.swift
  SideDishApp/SideDishApp/SupportingFiles/Assets.xcassets/AccentColor.colorset/Contents.json
  SideDishApp/SideDishApp/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  SideDishApp/SideDishApp/SupportingFiles/Assets.xcassets/Contents.json
  SideDishApp/SideDishApp/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  SideDishApp/SideDishApp/SupportingFiles/Constant.swift
  SideDishApp/SideDishApp/SupportingFiles/SceneDelegate.swift
  SideDishApp/SideDishApp/SupportingFiles/mockImage.png
  SideDishApp/SideDishApp/View/OrderingCollectionViewCell.swift
  SideDishApp/SideDishApp/View/SectionHeaderView.swift
  SideDishApp/SideDishInfo.swift
Labels: review-iOS

#37 [Team-31 BE 노리 & 휘] Side-dish 프로젝트 1주차(수요일) 코드 리뷰 요청
  README.md
  backend/README.md
Labels: review-BE

#27 [team28 - Backend] 프로젝트 초기 셋팅, DB 설계, API 설계, Mock API 구현 중
  .github/ISSUE_TEMPLATE/issue-template.md
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/team28/sidedish/SidedishApplication.java
  backend/src/main/java/com/team28/sidedish/config/SwaggerConfig.java
  backend/src/main/java/com/team28/sidedish/controller/CategoryController.java
  backend/src/main/java/com/team28/sidedish/controller/ProductController.java
  backend/src/main/java/com/team28/sidedish/controller/dto/CategoryResponse.java
  backend/src/main/java/com/team28/sidedish/controller/dto/ProductListResponse.java
  backend/src/main/java/com/team28/sidedish/controller/dto/ProductResponse.java
  backend/src/main/java/com/team28/sidedish/service/CategoryService.java
  backend/src/main/java/com/team28/sidedish/service/MockCategoryService.java
  backend/src/main/java/com/team28/sidedish/service/MockProductService.java
  backend/src/main/java/com/team28/sidedish/service/ProductService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/team28/sidedish/SidedishApplicationTests.java
Labels: review-BE

#44 [Team-13][BE] 반찬가게 프로젝트 1주차 첫 PR입니다 (DB 설계 및 API 명세 작성)
  README.md
  backend/.gitignore
  backend/HELP.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/kr/codesquad/sidedish/SidedishApplication.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/sql/schema.sql
  backend/src/test/java/kr/codesquad/sidedish/SidedishApplicationTests.java
Labels: review-BE

#19 [Team-5 BE 익조 & 피오] Sidedish 프로젝트 1주차(수요일) 코드 리뷰 요청
  BE/src/main/java/com/sidedish/controller/EventCategoryController.java
  BE/src/main/java/com/sidedish/domain/Event.java
  BE/src/main/java/com/sidedish/domain/EventCategory.java
  BE/src/main/java/com/sidedish/dto/EventCategoryDto.java
  BE/src/main/java/com/sidedish/dto/EventCategoryListDto.java
  BE/src/main/java/com/sidedish/repository/EventCategoryRepository.java
  BE/src/main/java/com/sidedish/repository/EventRepository.java
  BE/src/main/java/com/sidedish/service/EventCategoryService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-BE

#16 [team-31][FE] 아울 & 올리버 1주차 첫 PR
  frontend/sidedish/.gitignore
  frontend/sidedish/README.md
  frontend/sidedish/package.json
  frontend/sidedish/public/images/cartIcon.png
  frontend/sidedish/public/images/searchIcon.png
  frontend/sidedish/public/images/userIcon.png
  frontend/sidedish/public/index.html
  frontend/sidedish/src/App.jsx
  frontend/sidedish/src/Gnb.jsx
  frontend/sidedish/src/Header.jsx
  frontend/sidedish/src/ItemCard.jsx
  frontend/sidedish/src/ItemCards.jsx
  frontend/sidedish/src/Label.jsx
  frontend/sidedish/src/Main.jsx
  frontend/sidedish/src/MenuTypeList.jsx
  frontend/sidedish/src/constants.jsx
  frontend/sidedish/src/index.js
  frontend/sidedish/src/mockData.json
  frontend/sidedish/yarn.lock
Labels: review-FE

#26 [team-06][FE] Header Component 생성
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/Mypage.svg
  fe/public/Search.svg
  fe/public/Shopping-cart.svg
  fe/public/index.html
  fe/public/mockServiceWorker.js
  fe/src/App.jsx
  fe/src/Header/Header.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/MenuList.jsx
  fe/src/Header/UserButtons.jsx
  fe/src/index.css
  fe/src/index.js
  fe/src/mocks/browser.js
  fe/src/mocks/handlers.js
Labels: review-FE

#38 [team-04][BE] sidedish 1주차 첫번째 PR #1
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/sidedish/SidedishApplication.java
  BE/src/main/java/kr/codesquad/sidedish/controller/MainController.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Category.java
  BE/src/main/java/kr/codesquad/sidedish/domain/DeliveryType.java
  BE/src/main/java/kr/codesquad/sidedish/domain/DiscountPolicy.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Dish.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Image.java
  BE/src/main/java/kr/codesquad/sidedish/dto/ApiResponse.java
  BE/src/main/java/kr/codesquad/sidedish/dto/DishSimpleResponse.java
  BE/src/main/java/kr/codesquad/sidedish/repository/JdbcCategoryRepository.java
  BE/src/main/java/kr/codesquad/sidedish/repository/JdbcDishRepository.java
  BE/src/main/java/kr/codesquad/sidedish/repository/JdbcImageRepository.java
  BE/src/main/java/kr/codesquad/sidedish/service/MainService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/kr/codesquad/sidedish/SidedishApplicationTests.java
  BE/src/test/java/kr/codesquad/sidedish/repository/JdbcCategoryRepositoryTest.java
  BE/src/test/java/kr/codesquad/sidedish/repository/JdbcDishRepositoryTest.java
Labels: review-BE

#41 [Team-18] Eddy & Kai 프로젝트 설계 및 네트워크, 모델 구현
  README.md
  SideDishApp/Podfile
  SideDishApp/Podfile.lock
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp/Common/Extension.swift
  SideDishApp/SideDishApp/Common/SystemLog.swift
  SideDishApp/SideDishApp/Model/Badge.swift
  SideDishApp/SideDishApp/Model/Category.swift
  SideDishApp/SideDishApp/Model/Delivery.swift
  SideDishApp/SideDishApp/Model/DetailData.swift
  SideDishApp/SideDishApp/Model/Money.swift
  SideDishApp/SideDishApp/Model/Product.swift
  SideDishApp/SideDishApp/Model/ProductDetail.swift
  SideDishApp/SideDishApp/Model/ProductType.swift
  SideDishApp/SideDishApp/Networking/NetworkError.swift
  SideDishApp/SideDishApp/Networking/NetworkManager.swift
  SideDishApp/SideDishApp/Service/CategoryManager.swift
  SideDishApp/SideDishAppTests/CategoryManagerTests.swift
  SideDishApp/SideDishAppTests/NetworkManagerTests.swift
  SideDishApp/SideDishAppTests/ProductDecodingTests.swift
  SideDishApp/SideDishAppTests/ProductDetailDecodingTest.swift
  SideDishApp/SideDishAppTests/resources/1155_ZIP_P_0081_T.jpg
  SideDishApp/SideDishAppTests/resources/mockProductData.json
  SideDishApp/SideDishAppTests/resources/mockProductDetailData.json
Labels: review-iOS

#34 [Team-14][FE] Jamie & 옐로우 1주차 첫 번째 PR
  .github/ISSUE_TEMPLATE/team-14----------.md
  BE/BE-sidedish/.gitignore
  BE/BE-sidedish/HELP.md
  BE/BE-sidedish/build.gradle
  BE/BE-sidedish/gradle/wrapper/gradle-wrapper.jar
  BE/BE-sidedish/gradle/wrapper/gradle-wrapper.properties
  BE/BE-sidedish/gradlew
  BE/BE-sidedish/gradlew.bat
  BE/BE-sidedish/settings.gradle
  BE/BE-sidedish/src/main/java/team14/sidedish/SidedishApplication.java
  BE/BE-sidedish/src/main/resources/application.properties
  BE/BE-sidedish/src/test/java/team14/sidedish/SidedishApplicationTests.java
  FE/fe-sidedish/.gitignore
  FE/fe-sidedish/README.md
  FE/fe-sidedish/package-lock.json
  FE/fe-sidedish/package.json
  FE/fe-sidedish/public/favicon.ico
  FE/fe-sidedish/public/index.html
  FE/fe-sidedish/public/logo192.png
  FE/fe-sidedish/public/logo512.png
  FE/fe-sidedish/public/manifest.json
  FE/fe-sidedish/public/robots.txt
  FE/fe-sidedish/src/App.js
  FE/fe-sidedish/src/asset/icons/cart.svg
  FE/fe-sidedish/src/asset/icons/index.js
  FE/fe-sidedish/src/asset/icons/left.svg
  FE/fe-sidedish/src/asset/icons/minus.svg
  FE/fe-sidedish/src/asset/icons/mypage.svg
  FE/fe-sidedish/src/asset/icons/plus.svg
  FE/fe-sidedish/src/asset/icons/right.svg
  FE/fe-sidedish/src/asset/icons/search.svg
  FE/fe-sidedish/src/components/card/Card.jsx
  FE/fe-sidedish/src/components/header/Categories.jsx
  FE/fe-sidedish/src/components/header/Header.jsx
  FE/fe-sidedish/src/components/header/IconMenu.jsx
  FE/fe-sidedish/src/components/header/Menus.jsx
  FE/fe-sidedish/src/components/header/SubCategories.jsx
  FE/fe-sidedish/src/components/pages/Main.jsx
  FE/fe-sidedish/src/components/pages/NotFound.jsx
  FE/fe-sidedish/src/data/dishes.js
  FE/fe-sidedish/src/data/iconMenus.js
  FE/fe-sidedish/src/data/nav.js
  FE/fe-sidedish/src/index.css
  FE/fe-sidedish/src/index.js
  FE/fe-sidedish/src/styles/base/_font.scss
  FE/fe-sidedish/src/styles/base/_reset.scss
  FE/fe-sidedish/src/styles/base/_variables.scss
  FE/fe-sidedish/src/styles/base/app.scss
  FE/fe-sidedish/src/styles/components/card.scss
  FE/fe-sidedish/src/styles/components/header.scss
Labels: review-FE

#8 [BE][Team-26] 1주차 1차 PR
  Android/README.md
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/docker/local-db.yml
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/sidedish/jbc/JbcApplication.java
  BE/src/main/java/sidedish/jbc/controller/MenuController.java
  BE/src/main/java/sidedish/jbc/domain/Menu.java
  BE/src/main/java/sidedish/jbc/domain/MenuType.java
  BE/src/main/java/sidedish/jbc/domain/SaleType.java
  BE/src/main/java/sidedish/jbc/dto/ResponseMenu.java
  BE/src/main/java/sidedish/jbc/repository/MenuRepository.java
  BE/src/main/java/sidedish/jbc/service/MenuService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/sidedish/jbc/JbcApplicationTests.java
  README.md
Labels: review-BE

#31 [Team-27][BE] Lucid & 산토리 - 1주차 1차 PR
  .github/ISSUE_TEMPLATE/------.md
  README.md
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/codesquad/sidedish/SidedishApplication.java
  backend/src/main/java/com/codesquad/sidedish/item/controller/ViewController.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/Category.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/DiscountPolicy.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/Item.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/ItemImage.java
  backend/src/main/java/com/codesquad/sidedish/item/dto/CategoryItemDto.java
  backend/src/main/java/com/codesquad/sidedish/item/dto/CategoryItemsDto.java
  backend/src/main/java/com/codesquad/sidedish/item/dto/DetailItemDto.java
  backend/src/main/java/com/codesquad/sidedish/item/dto/ItemDto.java
  backend/src/main/java/com/codesquad/sidedish/item/service/ViewService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/codesquad/sidedish/SidedishApplicationTests.java
Labels: review-BE

#9 [team-10][FE][이든, Khan] 반찬가게 Step1
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/assets/arrowLeft.png
  public/assets/arrowRight.png
  public/assets/basket.png
  public/assets/minus.png
  public/assets/plus.png
  public/assets/search.png
  public/assets/user.png
  public/data/mainCard.json
  public/data/mainDish.json
  public/data/sideDish.json
  public/data/soup.json
  public/index.html
  src/App.js
  src/Header.js
  src/MainCard.js
  src/css/mixins.js
  src/css/variables.js
  src/index.js
  src/utility/util.js
Labels: review-FE

#40 [team-8][FE] 베니 & 포키 1주차 첫 PR
  .github/ISSUE_TEMPLATE/---feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  app/.eslintrc.js
  app/.gitignore
  app/README.md
  app/build/asset-manifest.json
  app/build/images/Cart.svg
  app/build/images/Left.svg
  app/build/images/Minus.svg
  app/build/images/MyPage.svg
  app/build/images/Plus.svg
  app/build/images/Right.svg
  app/build/images/Search.svg
  app/build/index.html
  app/build/static/js/main.c0b141a3.js
  app/build/static/js/main.c0b141a3.js.LICENSE.txt
  app/build/static/js/main.c0b141a3.js.map
  app/package-lock.json
  app/package.json
  app/public/images/Cart.svg
  app/public/images/Left.svg
  app/public/images/Minus.svg
  app/public/images/MyPage.svg
  app/public/images/Plus.svg
  app/public/images/Right.svg
  app/public/images/Search.svg
  app/public/index.html
  app/src/components/App.js
  app/src/components/Card.js
  app/src/components/CardList.js
  app/src/components/Header.js
  app/src/components/MainTab.js
  app/src/index.js
  app/src/store/store.js
  app/src/styles/theme.js
Labels: review-FE

#35 [team-04][FE] 도비 & Muffin PR 1주차
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/issue-template.md
  README.md
  fe/.gitignore
  fe/.prettierrc.json
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.jsx
  fe/src/GlobalStyles.jsx
  fe/src/Header/HeaderCategory.jsx
  fe/src/Header/HeaderTemplate.jsx
  fe/src/Main/Card.jsx
  fe/src/Main/Dish/DishCategoryAllButton.jsx
  fe/src/Main/Dish/DishContainer.jsx
  fe/src/Main/Recommend/RecommendProduct.jsx
  fe/src/Main/Recommend/RecommendTab.jsx
  fe/src/Main/Recommend/RecommendTabList.jsx
  fe/src/image/cart.svg
  fe/src/image/leftArrow.svg
  fe/src/image/minus.svg
  fe/src/image/person.svg
  fe/src/image/plus.svg
  fe/src/image/rightArrow.svg
  fe/src/image/search.svg
  fe/src/index.js
  fe/src/theme.jsx
Labels: review-FE

#55 [Team-02][FE] 1주차 첫 번째 PR
  .github/ISSUE_TEMPLATE/feature.md
  README.md
  backend/README.md
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icon/eventLabel-icon.svg
  frontend/public/icon/launchingLabel-icon.svg
  frontend/public/icon/myCart-icon.svg
  frontend/public/icon/pageHeader-icon.svg
  frontend/public/icon/search-icon.svg
  frontend/public/icon/specialPromotion-icon.svg
  frontend/public/icon/user-icon.svg
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/css/GoodsBlock.css
  frontend/src/css/Header.css
  frontend/src/css/SpecialPromotion.css
  frontend/src/css/reset.css
  frontend/src/index.js
  frontend/src/js/components/GoodsBlock.js
  frontend/src/js/components/Header.js
  frontend/src/js/components/SpecialPromotion.js
  frontend/src/js/constants/iconPath.js
  frontend/src/js/data/category.js
  frontend/src/js/data/goods.js
Labels: review-FE

#11 [Team24][iOS] 반찬리스트 뷰 구현과 화면이동
  .gitignore
  README.md
  iOS/README.md
  iOS/SideDish-team24/Podfile
  iOS/SideDish-team24/Podfile.lock
  iOS/SideDish-team24/SideDish-team24.xcodeproj/project.pbxproj
  iOS/SideDish-team24/SideDish-team24.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/SideDish-team24/SideDish-team24.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/SideDish-team24/SideDish-team24.xcworkspace/contents.xcworkspacedata
  iOS/SideDish-team24/SideDish-team24.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/SideDish-team24/SideDish-team24/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/SideDish-team24/SideDish-team24/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/SideDish-team24/SideDish-team24/Assets.xcassets/Contents.json
  iOS/SideDish-team24/SideDish-team24/Base.lproj/LaunchScreen.storyboard
  iOS/SideDish-team24/SideDish-team24/Base.lproj/Main.storyboard
  iOS/SideDish-team24/SideDish-team24/Delegate/AppDelegate.swift
  iOS/SideDish-team24/SideDish-team24/Delegate/SceneDelegate.swift
  iOS/SideDish-team24/SideDish-team24/Extension/BriefBanchanViewControllerExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/CGFloatExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/StringExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/UIColorExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/UILabelExtension.swift
  iOS/SideDish-team24/SideDish-team24/Info.plist
  iOS/SideDish-team24/SideDish-team24/Model/Dish.swift
  iOS/SideDish-team24/SideDish-team24/Model/Dishes.swift
  iOS/SideDish-team24/SideDish-team24/View/BriefBanchanReusableView.swift
  iOS/SideDish-team24/SideDish-team24/View/BriefBanchanViewCell.swift
  iOS/SideDish-team24/SideDish-team24/View/DeliverySectionView.swift
  iOS/SideDish-team24/SideDish-team24/View/DetailBanchanBriefView.swift
  iOS/SideDish-team24/SideDish-team24/ViewController/BriefBanchanViewController.swift
  iOS/SideDish-team24/SideDish-team24/ViewController/DetailBanchanViewController.swift
  iOS/SideDish-team24/SideDish-team24/ViewController/MainViewController.swift
Labels: review-iOS

#7 [team-25] 화면 흐름 설계하기
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  SideDishProject/.swiftlint.yml
  SideDishProject/Podfile
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SideDishProject/SideDishProject.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SideDishProject/SideDishProject/AppDelegate.swift
  SideDishProject/SideDishProject/Assets.xcassets/AccentColor.colorset/Contents.json
  SideDishProject/SideDishProject/Assets.xcassets/AppIcon.appiconset/Contents.json
  SideDishProject/SideDishProject/Assets.xcassets/Contents.json
  SideDishProject/SideDishProject/Base.lproj/LaunchScreen.storyboard
  SideDishProject/SideDishProject/DetailViewController.swift
  SideDishProject/SideDishProject/HomeView.swift
  SideDishProject/SideDishProject/HomeViewController.swift
  SideDishProject/SideDishProject/Info.plist
  SideDishProject/SideDishProject/Product.swift
  SideDishProject/SideDishProject/ProductFactory.swift
  SideDishProject/SideDishProject/ProductRepository.swift
  SideDishProject/SideDishProject/RootNavigationController.swift
  SideDishProject/SideDishProject/SceneDelegate.swift
  SideDishProject/SideDishProjectTests/SideDishProjectTests.swift
  SideDishProject/SideDishProjectUITests/SideDishProjectUITests.swift
  SideDishProject/SideDishProjectUITests/SideDishProjectUITestsLaunchTests.swift
Labels: review-iOS

#17 [Team34][FE][JS&Geon] 1주차 수요일 pr
  front/.gitignore
  front/.prettierrc
  front/README.md
  front/package-lock.json
  front/package.json
  front/public/index.html
  front/src/App.js
  front/src/GlobalStyles.js
  front/src/components/Card.js
  front/src/components/Header.js
  front/src/components/Modal.js
  front/src/images/Logo.svg
  front/src/images/Mypage.svg
  front/src/images/Shopping-cart.svg
  front/src/images/search.svg
  front/src/index.js
Labels: review-FE

#42 [Team-19 iOS Chez & Jason] SideDish - ViewController에 출력확인
  .DS_Store
  .gitignore
  sideDish/Podfile
  sideDish/Podfile.lock
  sideDish/sideDish.xcodeproj/project.pbxproj
  sideDish/sideDish.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  sideDish/sideDish.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sideDish/sideDish.xcworkspace/contents.xcworkspacedata
  sideDish/sideDish.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sideDish/sideDish/AppDelegate.swift
  sideDish/sideDish/CollectionHeaderView.swift
  sideDish/sideDish/Info.plist
  sideDish/sideDish/JSON/JsonConvertor.swift
  sideDish/sideDish/JSON/mock.json
  sideDish/sideDish/Model/Food.swift
  sideDish/sideDish/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  sideDish/sideDish/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  sideDish/sideDish/Resource/Assets.xcassets/Contents.json
  sideDish/sideDish/Resource/Assets.xcassets/tempFood.imageset/Contents.json
  sideDish/sideDish/Resource/Assets.xcassets/tempFood.imageset/Image.png
  sideDish/sideDish/Resource/Base.lproj/LaunchScreen.storyboard
  sideDish/sideDish/Resource/Base.lproj/Main.storyboard
  sideDish/sideDish/SceneDelegate.swift
  sideDish/sideDish/View/FoodCell.swift
  sideDish/sideDish/ViewController/MainViewController.swift
Labels: review-iOS

#52 [team-01][FE] 프로젝트 초기 세팅, Styled Components 적용
  FE/.gitignore
  FE/.prettierrc
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.js
  FE/src/Header.jsx
  FE/src/Header.style.js
  FE/src/assets/cart.svg
  FE/src/assets/login.svg
  FE/src/assets/logo.svg
  FE/src/assets/search.svg
  FE/src/index.js
  FE/src/style/global.js
  FE/src/style/theme.js
  README.md
Labels: review-FE

#49 [Team-25 데이먼 & 벅픽] Side-dish 1주차 수요일 PR (프로젝트 초기설정, DB 설계, API 설계, Entity 클래스 생성)
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/team25/sidedish/SidedishApplication.java
  BE/src/main/java/com/team25/sidedish/domain/Category.java
  BE/src/main/java/com/team25/sidedish/domain/Delivery.java
  BE/src/main/java/com/team25/sidedish/domain/DeliveryType.java
  BE/src/main/java/com/team25/sidedish/domain/Event.java
  BE/src/main/java/com/team25/sidedish/domain/Image.java
  BE/src/main/java/com/team25/sidedish/domain/Product.java
  BE/src/main/java/com/team25/sidedish/domain/ProductDelivery.java
  BE/src/main/java/com/team25/sidedish/domain/ProductEvent.java
  BE/src/main/java/com/team25/sidedish/exception/ErrorResponse.java
  BE/src/main/java/com/team25/sidedish/exception/NotFoundException.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
  BE/src/main/resources/logback-spring.xml
  BE/src/test/java/com/team25/sidedish/SidedishApplicationTests.java
Labels: review-BE

#47 [Team 21] [iOS] UI 및 URLSession 구현
  .gitignore
  README.md
  sidedish/.swiftlint.yml
  sidedish/Podfile
  sidedish/Podfile.lock
  sidedish/sidedish.xcodeproj/project.pbxproj
  sidedish/sidedish.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  sidedish/sidedish.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sidedish/sidedish.xcworkspace/contents.xcworkspacedata
  sidedish/sidedish.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sidedish/sidedish/Configuration/Info.plist
  sidedish/sidedish/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  sidedish/sidedish/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  sidedish/sidedish/Resources/Assets.xcassets/Contents.json
  sidedish/sidedish/Resources/Assets.xcassets/testimage.imageset/Contents.json
  sidedish/sidedish/Resources/Assets.xcassets/testimage.imageset/testimage.png
  sidedish/sidedish/Sources/API/Base/ApiResult.swift
  sidedish/sidedish/Sources/API/Base/EndPoint.swift
  sidedish/sidedish/Sources/API/Base/HTTPMethod.swift
  sidedish/sidedish/Sources/API/SidedishEndPoint.swift
  sidedish/sidedish/Sources/AppDelegate.swift
  sidedish/sidedish/Sources/Common/MenuInfoView.swift
  sidedish/sidedish/Sources/Common/PaddingLabel.swift
  sidedish/sidedish/Sources/Extension/String+Extension.swift
  sidedish/sidedish/Sources/Extension/UIConrtol+Extension.swift
  sidedish/sidedish/Sources/Model/MenuDetail.swift
  sidedish/sidedish/Sources/Model/Sidedish.swift
  sidedish/sidedish/Sources/Present/Login/LoginViewController.swift
  sidedish/sidedish/Sources/Present/Main/CollectionViewHeader.swift
  sidedish/sidedish/Sources/Present/Main/CustomCollectionCell.swift
  sidedish/sidedish/Sources/Present/Main/MainViewController.swift
  sidedish/sidedish/Sources/Present/Main/MainViewModel.swift
  sidedish/sidedish/Sources/Present/MenuDetail/MenuDetailViewController.swift
  sidedish/sidedish/Sources/Present/MenuDetail/MenuDetailViewModel.swift
  sidedish/sidedish/Sources/Present/MenuDetail/View/MenuAmountView.swift
  sidedish/sidedish/Sources/Present/MenuDetail/View/MenuOrderView.swift
  sidedish/sidedish/Sources/Present/MenuDetail/View/MenuSubInfoView.swift
  sidedish/sidedish/Sources/Present/MenuDetail/View/ThumbnailImageView.swift
  sidedish/sidedish/Sources/Repository/Base/NetworkResult.swift
  sidedish/sidedish/Sources/Repository/Base/SessionError.swift
  sidedish/sidedish/Sources/Repository/Base/URLSessionProtocol.swift
  sidedish/sidedish/Sources/Repository/Base/URLSessionProvider.swift
  sidedish/sidedish/Sources/Repository/NetworkRepository.swift
  sidedish/sidedish/Sources/Repository/Sidedish/SidedishRepository.swift
  sidedish/sidedish/Sources/Repository/Sidedish/SidedishRepositoryImpl.swift
  sidedish/sidedish/Sources/SceneDelegate.swift
  sidedish/sidedish/Sources/UIColor+Extention.swift
Labels: review-iOS

#97 [JinSol] UI: CollectionView 구성요소 간격 조정 및 DetailView 구현
  SideDish/SideDish.xcodeproj/project.pbxproj
  SideDish/SideDish/Base/AppDelegate.swift
  SideDish/SideDish/Base/Base.lproj/Main.storyboard
  SideDish/SideDish/Base/Info.plist
  SideDish/SideDish/Base/SceneDelegate.swift
  SideDish/SideDish/Extensions/UIColor+.swift
  SideDish/SideDish/Support/Font.swift
  SideDish/SideDish/View/DetailView.swift
  SideDish/SideDish/View/DetailViewController.swift
  SideDish/SideDish/View/DishCell.swift
  SideDish/SideDish/View/DishCell.xib
  SideDish/SideDish/View/HomeViewController.swift
  SideDish/SideDish/View/PaddingLabel.swift
  SideDish/SideDish/View/SectionHeader.swift
Labels: review-iOS

#75 [team-15] iOS - bibi & puco 두 번째 PR 드립니다!
  sidedishApp/sidedishApp.xcodeproj/project.pbxproj
  sidedishApp/sidedishApp/Base.lproj/Main.storyboard
  sidedishApp/sidedishApp/CardFactory.swift
  sidedishApp/sidedishApp/DetailViewController.swift
  sidedishApp/sidedishApp/FirstSectionViewController.swift
  sidedishApp/sidedishApp/Info.plist
  sidedishApp/sidedishApp/MainViewCardCell.swift
  sidedishApp/sidedishApp/SecondSectionViewController.swift
  sidedishApp/sidedishApp/ThirdSectionViewController.swift
  sidedishApp/sidedishApp/font/SFProDisplay-Regular.OTF
  sidedishApp/sidedishApp/font/SFProDisplay-Semibold.otf
  sidedishApp/sidedishApp/model/DetailCard.swift
  sidedishApp/sidedishApp/model/MainCard.swift
  sidedishApp/sidedishApp/viewController/detail/DetailViewController.swift
  sidedishApp/sidedishApp/viewController/detail/MainDescriptionViewController.swift
  sidedishApp/sidedishApp/viewController/detail/OrderViewController.swift
  sidedishApp/sidedishApp/viewController/detail/SubDescriptionViewController.swift
  sidedishApp/sidedishApp/viewController/main/MainViewCardCell.swift
  sidedishApp/sidedishApp/viewController/main/MainViewController.swift
  sidedishApp/sidedishApp/viewController/main/MainViewHeader.swift
Labels: review-iOS

#99 [team 13] [FE] mock data를 이용한 메인 페이지 마크업
  README.md
  frontend/README.md
  frontend/public/categories.json
  frontend/public/mocks/categories.json
  frontend/public/mocks/categoryProducts.json
  frontend/public/mocks/specialCategories.json
  frontend/public/mocks/specialCategoryProducts.json
  frontend/src/App.js
  frontend/src/components/BestProduct.js
  frontend/src/components/Button.js
  frontend/src/components/CardList.js
  frontend/src/components/Category.js
  frontend/src/components/DiscountTag.js
  frontend/src/components/GnbMenu.js
  frontend/src/components/Header.js
  frontend/src/components/ProductCard.js
  frontend/src/convention.js
  frontend/src/fetcher.js
  frontend/src/index.js
  frontend/src/styles/global.js
  frontend/src/styles/theme.js
  frontend/yarn.lock
Labels: review-FE

#98 [Team-13][BE] 카테고리 목록 조회 구현
  backend/.gitignore
  backend/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
  backend/src/main/java/kr/codesquad/sidedish/controller/dto/CategoryListResponse.java
  backend/src/main/java/kr/codesquad/sidedish/domain/Category.java
  backend/src/main/java/kr/codesquad/sidedish/domain/Subcategory.java
  backend/src/main/java/kr/codesquad/sidedish/repository/CategoryRepository.java
  backend/src/main/java/kr/codesquad/sidedish/service/CategoryService.java
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/schema.sql
  backend/src/test/java/kr/codesquad/sidedish/service/CategoryServiceTest.java
Labels: review-BE

#67 [Team-5 BE 익조 & 피오] Sidedish 프로젝트 1주차(금요일) 코드 리뷰 요청
  BE/src/main/java/com/sidedish/controller/EventCategoryController.java
  BE/src/main/java/com/sidedish/controller/SideDishController.java
  BE/src/main/java/com/sidedish/domain/Event.java
  BE/src/main/java/com/sidedish/domain/EventCategory.java
  BE/src/main/java/com/sidedish/domain/ImageFile.java
  BE/src/main/java/com/sidedish/domain/SideDish.java
  BE/src/main/java/com/sidedish/dto/EventCategoryDto.java
  BE/src/main/java/com/sidedish/dto/EventCategoryListDto.java
  BE/src/main/java/com/sidedish/dto/SideDishDto.java
  BE/src/main/java/com/sidedish/dto/SideDishListDto.java
  BE/src/main/java/com/sidedish/mapper/EventCategoryMapper.java
  BE/src/main/java/com/sidedish/mapper/SideDishMapper.java
  BE/src/main/java/com/sidedish/repository/EventCategoryRepository.java
  BE/src/main/java/com/sidedish/repository/EventRepository.java
  BE/src/main/java/com/sidedish/repository/SideDishRepository.java
  BE/src/main/java/com/sidedish/service/EventCategoryService.java
  BE/src/main/java/com/sidedish/service/SideDishService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-BE

#95 [Team-14][BE] 1주차 첫 번째 PR
  BE/BE-sidedish/HELP.md
  BE/BE-sidedish/README.md
  BE/BE-sidedish/build.gradle
  BE/BE-sidedish/src/main/java/team14/sidedish/controller/SideDishController.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/Category.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/EventBadge.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/Menu.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/OrderInfo.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/SaleInfo.java
  BE/BE-sidedish/src/main/java/team14/sidedish/repository/EventBadgeRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/repository/SideDishRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/service/EventBadgeService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/service/SideDishService.java
  BE/BE-sidedish/src/main/resources/application.properties
  BE/BE-sidedish/src/main/resources/data.sql
  BE/BE-sidedish/src/main/resources/schemas.sql
Labels: review-BE

#87 [team-06][FE] 기획전, 카테고리 목록, Mock API 구현
  fe/.prettierrc
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/logo.svg
  fe/src/App.jsx
  fe/src/Badge/CategoryBadge.jsx
  fe/src/Badge/DiscountBadge.jsx
  fe/src/Constants/Colors.js
  fe/src/Header/Header.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/MenuList.jsx
  fe/src/Header/UserButtons.jsx
  fe/src/Main/BestProducts.jsx
  fe/src/Main/Category.jsx
  fe/src/Main/CategoryList.jsx
  fe/src/Main/Main.jsx
  fe/src/Main/ProductCard.jsx
  fe/src/index.css
  fe/src/mocks/handlers.js
Labels: review-FE

#68 [team-32][FE][otter, jinnie] 2번째 PR 요청
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.js
  fe/src/asset/cartIcon.svg
  fe/src/asset/leftIcon.svg
  fe/src/asset/myPageIcon.svg
  fe/src/asset/rightIcon.svg
  fe/src/asset/searchIcon.svg
  fe/src/component/Header/CustomNav.js
  fe/src/component/Header/GNB.js
  fe/src/component/Header/Header.css
  fe/src/component/Header/Header.js
  fe/src/component/Header/Icons.js
  fe/src/component/SubTitle/SubTitle.js
  fe/src/component/Tab/List.js
  fe/src/component/Tab/Tab.css
  fe/src/component/Tab/Tab.js
  fe/src/component/UI/Card.css
  fe/src/component/UI/Card.js
  fe/src/component/UI/CardsWrapper.js
  fe/src/component/bottom/Slide.js
  fe/src/component/bottom/SlideIcon.js
Labels: review-FE

#80 [team-04][FE] 도비 & Muffin PR 1주차 금 PR
  fe/jsconfig.json
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.jsx
  fe/src/Header/HeaderCategory.jsx
  fe/src/Header/HeaderTemplate.jsx
  fe/src/Main/Card.jsx
  fe/src/Main/CardDeliveryInfo.jsx
  fe/src/Main/Dish/DishCategoryAllButton.jsx
  fe/src/Main/Dish/DishContainer.jsx
  fe/src/Main/MainContainer.jsx
  fe/src/Main/Recommend/RecommendProduct.jsx
  fe/src/Main/Recommend/RecommendTab.jsx
  fe/src/Main/Recommend/RecommendTabList.jsx
  fe/src/MockData/dummyData.js
  fe/src/theme.jsx
Labels: review-FE

#90 [Team-07] [FE] [ver & S] 두번째 PR
  FE/babel.config.js
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
  FE/src/App.scss
  FE/src/assets/image/cart.svg
  FE/src/assets/image/logo.svg
  FE/src/assets/image/logo1.svg
  FE/src/assets/image/myPage.svg
  FE/src/assets/image/search.svg
  FE/src/components/Header/Header.js
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/Header.scss
  FE/src/components/Promotion/Promotion.jsx
  FE/src/components/Promotion/Promotion.scss
  FE/src/index.js
  FE/webpack.config.js
Labels: review-FE

#91 [BE][Team-07][반스&케이] 1주차 금요일 PR
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/kr/codesquad/sidedish/controller/ItemController.java
  BE/src/main/java/kr/codesquad/sidedish/domain/BestType.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Category.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Delivery.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Image.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Item.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Label.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Order.java
  BE/src/main/java/kr/codesquad/sidedish/domain/User.java
  BE/src/main/java/kr/codesquad/sidedish/repository/CategoryRepository.java
  BE/src/main/java/kr/codesquad/sidedish/repository/ItemRepository.java
  BE/src/main/java/kr/codesquad/sidedish/repository/OrderRepository.java
  BE/src/main/java/kr/codesquad/sidedish/service/ItemService.java
  BE/src/main/java/kr/codesquad/sidedish/web/dto/item/ItemListResponseDto.java
  BE/src/main/java/kr/codesquad/sidedish/web/dto/item/ItemResponseDto.java
  BE/src/main/java/kr/codesquad/sidedish/web/dto/order/OrderRequestDto.java
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-BE

#64 [TEAM-06] Side-dish 프로젝트 1주차 2번째 pr
  be/build.gradle
  be/src/main/java/sidedish/domain/category/CategoryRepository.java
  be/src/main/java/sidedish/domain/category/EventCategory.java
  be/src/main/java/sidedish/domain/category/MainCategory.java
  be/src/main/java/sidedish/domain/category/SubCategory.java
  be/src/main/java/sidedish/domain/images/Images.java
  be/src/main/java/sidedish/domain/item/Item.java
  be/src/main/java/sidedish/domain/item/ItemRepository.java
  be/src/main/java/sidedish/domain/order/Order.java
  be/src/main/java/sidedish/service/CategoryService.java
  be/src/main/java/sidedish/service/ItemService.java
  be/src/main/java/sidedish/web/controller/CategoryController.java
  be/src/main/java/sidedish/web/controller/ItemController.java
  be/src/main/java/sidedish/web/dto/ResponseDto.java
  be/src/main/java/sidedish/web/dto/category/ResponseEventsDto.java
  be/src/main/java/sidedish/web/dto/item/ResponseItemDto.java
  be/src/main/java/sidedish/web/dto/order/RequestOrderDto.java
  be/src/main/resources/application.properties
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: review-BE

#106 [Team-12 BE] 1주차 두번째 PR (2022/4/22)
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/src/docs/asciidoc/index.adoc
  BE/src/main/java/com/sidedish/api/categories/CategoryController.java
  BE/src/main/java/com/sidedish/api/categories/DetailController.java
  BE/src/main/java/com/sidedish/api/categories/dto/ItemResource.java
  BE/src/main/java/com/sidedish/api/categories/dto/ResponseItemDto.java
  BE/src/main/java/com/sidedish/api/categories/dto/ResponseItems.java
  BE/src/main/java/com/sidedish/api/categories/initDB.java
  BE/src/main/java/com/sidedish/domain/CategoryType.java
  BE/src/main/java/com/sidedish/domain/Images.java
  BE/src/main/java/com/sidedish/domain/Item.java
  BE/src/main/java/com/sidedish/repository/ItemRepository.java
  BE/src/main/java/com/sidedish/service/CategoryService.java
  BE/src/main/java/com/sidedish/service/ItemService.java
  BE/src/main/resources/data/schema.sql
  BE/src/test/java/com/sidedish/SidedishApplicationTests.java
  BE/src/test/java/com/sidedish/api/categories/CategoryIntegrationTest.java
  BE/src/test/java/com/sidedish/common/RestDocsConfiguration.java
  BE/src/test/java/com/sidedish/domain/ItemOrderTest.java
  BE/src/test/java/com/sidedish/domain/ItemTest.java
Labels: review-BE

#92 [team-35] [bangtae & 호이] 1주차 두번째 PR
  fe/src/App.js
  fe/src/components/BestProduct.js
  fe/src/components/BestProduct/TapList.js
  fe/src/components/BestProduct/TapMenu.js
  fe/src/components/Card.js
  fe/src/components/Card.styled.js
  fe/src/components/Header.js
  fe/src/helper/constants.js
  fe/src/helper/mock.js
  fe/src/helper/utils.js
  fe/src/views/BestProduct.js
  fe/src/views/Header.js
  fe/src/views/bestProduct/BestProduct.styled.js
  fe/src/views/bestProduct/tabList.js
  fe/src/views/bestProduct/tabMenu.js
  fe/src/views/header/Header.styled.js
  fe/src/views/header/gnbLists.js
  fe/src/views/header/svg.js
Labels: review-FE

#78 [Team24][iOS] 수량 뷰 구현, 메소드 분리
  iOS/SideDish-team24/SideDish-team24.xcodeproj/project.pbxproj
  iOS/SideDish-team24/SideDish-team24/Extension/UIColorExtension.swift
  iOS/SideDish-team24/SideDish-team24/View/BriefBanchanReusableView.swift
  iOS/SideDish-team24/SideDish-team24/View/BriefBanchanViewCell.swift
  iOS/SideDish-team24/SideDish-team24/View/DeliverySectionView.swift
  iOS/SideDish-team24/SideDish-team24/View/DetailBanchanBriefView.swift
  iOS/SideDish-team24/SideDish-team24/View/OrderCountSectionView.swift
  iOS/SideDish-team24/SideDish-team24/ViewController/BriefBanchanViewController.swift
  iOS/SideDish-team24/SideDish-team24/ViewController/DetailBanchanViewController.swift
Labels: review-iOS

#105 [team28 - Backend] 코드리뷰 피드백 적용 및 AWS 배포
  README.md
  backend/src/main/java/com/team28/sidedish/controller/CategoryController.java
  backend/src/main/java/com/team28/sidedish/controller/OrderController.java
  backend/src/main/java/com/team28/sidedish/controller/ProductController.java
  backend/src/main/java/com/team28/sidedish/controller/dto/OrderRequest.java
  backend/src/main/java/com/team28/sidedish/controller/dto/ProductDetailResponse.java
  backend/src/main/java/com/team28/sidedish/controller/dto/ProductImageResponse.java
  backend/src/main/java/com/team28/sidedish/exception/ErrorResponse.java
  backend/src/main/java/com/team28/sidedish/service/MockCategoryService.java
  backend/src/main/java/com/team28/sidedish/service/MockOrderService.java
  backend/src/main/java/com/team28/sidedish/service/MockProductDetailService.java
  backend/src/main/java/com/team28/sidedish/service/MockProductImageService.java
  backend/src/main/java/com/team28/sidedish/service/MockProductService.java
Labels: review-BE

#111 [Team 09] [dony, rumka] 1주차 2번째 PR 요청드립니다.
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.jsx
  src/GlobalStyles.js
  src/Sidedish.jsx
  src/components/Button.jsx
  src/components/Card.jsx
  src/components/Header.jsx
  src/components/IconButton.jsx
  src/components/MoreButton.jsx
  src/components/TabBar.jsx
  src/components/TabButton.jsx
  src/components/Tag.jsx
  src/components/Text.jsx
  src/images/HoverInfo.png
  src/images/icon_cart.svg
  src/images/icon_minus.svg
  src/images/icon_next.svg
  src/images/icon_plus.svg
  src/images/icon_prev.svg
  src/images/icon_search.svg
  src/images/icon_user.svg
  src/index.jsx
  src/template/Template.jsx
  src/variable/color.js
  src/variable/font.js
Labels: review-FE

#76 [Team-5 FE BB & JinJeon] Sidedish 프로젝트 1주차(금요일) PR
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/Component/Header/Header.jsx
  fe/src/Component/Header/Header.styled.js
  fe/src/Component/Header/HeaderLeft/HeaderLeft.jsx
  fe/src/Component/Header/HeaderLeft/HeaderLeft.styled.js
  fe/src/Component/Header/HeaderLeft/Menu.Styled.js
  fe/src/Component/Header/HeaderLeft/Menu.jsx
  fe/src/Component/Header/HeaderLeft/Nav.jsx
  fe/src/Component/Header/HeaderLeft/Nav.styled.js
  fe/src/Component/Header/HeaderRight/HeaderRight.jsx
  fe/src/Component/Header/HeaderRight/HeaderRight.styled.js
  fe/src/MockData/MockData.jsx
  fe/src/Styles/Normalize.js
  fe/src/Styles/Reset.js
Labels: review-FE

#60 [Team-31 BE 노리 & 휘] Side-dish 프로젝트 1주차(금요일) 코드 리뷰 요청
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/team31/codesuqad/sidedish/SidedishApplication.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/schema.sql
  backend/src/test/java/team31/codesuqad/sidedish/SidedishApplicationTests.java
Labels: review-BE

#70 [team-32][BE][Heyho & 선을로] 1주차 2번째 PR 요청
  be/build.gradle
  be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
  be/src/main/java/kr/codesquad/sidedish/domain/Product.java
  be/src/main/java/kr/codesquad/sidedish/dto/DetailProductInfo.java
  be/src/main/java/kr/codesquad/sidedish/dto/ProductDTO.java
  be/src/main/java/kr/codesquad/sidedish/dto/RequestProduct.java
  be/src/main/java/kr/codesquad/sidedish/dto/SimpleProductInfo.java
  be/src/main/java/kr/codesquad/sidedish/repository/MemoryProductRepository.java
  be/src/main/java/kr/codesquad/sidedish/repository/ProductRepository.java
  be/src/main/java/kr/codesquad/sidedish/service/ProductService.java
  be/src/main/resources/application.properties
  be/src/main/resources/sql/data.sql
  be/src/main/resources/sql/schema.sql
Labels: review-BE

#102 [BE][[team-33] Miller, Nathan - dish/category 조회 및 배포 자동화 구현
  backend/deploy/back_deploy.sh
  backend/deploy/front_deploy.sh
  backend/src/main/java/com/codesquad/sidedish/category/Category.java
  backend/src/main/java/com/codesquad/sidedish/category/CategoryController.java
  backend/src/main/java/com/codesquad/sidedish/category/CategoryRepository.java
  backend/src/main/java/com/codesquad/sidedish/category/CategoryResponse.java
  backend/src/main/java/com/codesquad/sidedish/category/CategoryService.java
  backend/src/main/java/com/codesquad/sidedish/dish/DishController.java
  backend/src/main/java/com/codesquad/sidedish/dish/DishRepository.java
  backend/src/main/java/com/codesquad/sidedish/dish/DishRowMapper.java
  backend/src/main/java/com/codesquad/sidedish/dish/DishService.java
  backend/src/main/java/com/codesquad/sidedish/dish/domain/Dish.java
  backend/src/main/java/com/codesquad/sidedish/dish/domain/DishCategory.java
  backend/src/main/java/com/codesquad/sidedish/dish/domain/DishDelivery.java
  backend/src/main/java/com/codesquad/sidedish/dish/domain/DishImage.java
  backend/src/main/java/com/codesquad/sidedish/dish/dto/DishResponse.java
  backend/src/main/java/com/codesquad/sidedish/dish/dto/Slice.java
  backend/src/main/java/com/codesquad/sidedish/event_badge/EventBadgeRepository.java
  backend/src/main/java/com/codesquad/sidedish/event_badge/domain/DishEventBadge.java
  backend/src/main/java/com/codesquad/sidedish/event_badge/domain/EventBadge.java
  backend/src/main/java/com/codesquad/sidedish/event_badge/dto/EventBadgeResponse.java
  backend/src/main/java/com/codesquad/sidedish/other/domain/Delivery.java
  backend/src/main/java/com/codesquad/sidedish/util/MapperUtil.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/application.properties
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/schema.sql
  backend/src/test/java/com/codesquad/sidedish/CategoryRepositoryTest.java
  backend/src/test/java/com/codesquad/sidedish/DishRepositoryTest.java
  backend/src/test/java/com/codesquad/sidedish/EventBadgeRepositoryTest.java
Labels: review-BE

#79 [team-11] 1주차 2번째 PR Nick + J
  public/public_assets/Image/mypage.png
  public/public_assets/Image/search.png
  public/public_assets/Image/shopping-cart.png
  src/App.js
  src/Assets/CommonStyle.js
  src/Components/List.jsx
  src/Components/header/GNB.jsx
  src/Components/header/ListItem.jsx
  src/Components/header/main.jsx
  src/GlobalStyles.js
  src/index.js
Labels: review-FE

#66 [team-03][FE][쥬&도리] 1주차 두 번째 PR: 컴포넌트 단위 설계
  FE/.gitignore
  FE/.prettierrc
  FE/jsconfig.json
  FE/package-lock.json
  FE/package.json
  FE/src/App.jsx
  FE/src/components/BestMealCard/index.jsx
  FE/src/components/BestMealContainer/index.jsx
  FE/src/components/Loader/index.jsx
  FE/src/components/MealCard/index.jsx
  FE/src/components/MealContainer/index.jsx
  FE/src/constant/index.js
  FE/src/index.js
  FE/src/util/index.js
Labels: review-FE

#83 [team-01][FE] 기획전 UI & 기능 구현
  FE/.gitignore
  FE/src/App.js
  FE/src/Header.jsx
  FE/src/Header/Header.jsx
  FE/src/Header/Header.style.js
  FE/src/Special/Special.jsx
  FE/src/Special/Special.style.js
  FE/src/components/Card.jsx
  FE/src/components/Card.syle.js
  FE/src/data/headerMenu.js
  FE/src/data/specialTab.js
  FE/src/style/global.js
  FE/src/style/theme.js
  FE/src/utils/utils.js
Labels: review-FE

#71 [BE][Team-26] 1주차 2차 PR
  BE/README.md
  BE/build.gradle
  BE/src/main/java/sidedish/jbc/JbcApplication.java
  BE/src/main/java/sidedish/jbc/config/SwaggerConfig.java
  BE/src/main/java/sidedish/jbc/config/WebConfig.java
  BE/src/main/java/sidedish/jbc/controller/MenuController.java
  BE/src/main/java/sidedish/jbc/domain/Image.java
  BE/src/main/java/sidedish/jbc/domain/Menu.java
  BE/src/main/java/sidedish/jbc/domain/MenuOrder.java
  BE/src/main/java/sidedish/jbc/domain/MenuType.java
  BE/src/main/java/sidedish/jbc/domain/convertor/MenuTypeConvertor.java
  BE/src/main/java/sidedish/jbc/dto/DetailMenu.java
  BE/src/main/java/sidedish/jbc/dto/DetailMenuImages.java
  BE/src/main/java/sidedish/jbc/dto/DetailMenuResponse.java
  BE/src/main/java/sidedish/jbc/dto/MenuResponse.java
  BE/src/main/java/sidedish/jbc/dto/OrderRequest.java
  BE/src/main/java/sidedish/jbc/repository/ImageRepository.java
  BE/src/main/java/sidedish/jbc/repository/MenuRepository.java
  BE/src/main/java/sidedish/jbc/repository/OrderRepository.java
  BE/src/main/java/sidedish/jbc/service/MenuService.java
  BE/src/main/java/sidedish/jbc/service/OrderService.java
  BE/src/main/resources/application-deploy.yml
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-BE

#69 [Team-27][BE] Lucid & 산토리 - 1주차 2차 PR
  backend/src/main/java/com/codesquad/sidedish/item/controller/ItemController.java
  backend/src/main/java/com/codesquad/sidedish/item/controller/ViewController.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/Category.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/CategoryRepository.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/DiscountPolicy.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/Item.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/ItemRepository.java
  backend/src/main/java/com/codesquad/sidedish/item/dto/CategoryItemDto.java
  backend/src/main/java/com/codesquad/sidedish/item/dto/DetailItemDto.java
  backend/src/main/java/com/codesquad/sidedish/item/dto/ItemDto.java
  backend/src/main/java/com/codesquad/sidedish/item/exception/ItemIdNotFoundException.java
  backend/src/main/java/com/codesquad/sidedish/item/service/ItemService.java
  backend/src/main/java/com/codesquad/sidedish/item/service/ViewService.java
  backend/src/main/java/com/codesquad/sidedish/order/controller/OrderController.java
  backend/src/main/java/com/codesquad/sidedish/order/domain/Order.java
  backend/src/main/java/com/codesquad/sidedish/order/domain/OrderRepository.java
  backend/src/main/java/com/codesquad/sidedish/order/dto/OrderItemDto.java
  backend/src/main/java/com/codesquad/sidedish/order/service/OrderService.java
  backend/src/main/java/com/codesquad/sidedish/user/domain/User.java
  backend/src/main/java/com/codesquad/sidedish/user/domain/UserRepository.java
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: review-BE

#101 [team-8][FE] 베니 & 포키 1주차 두번째 PR
  app/build/asset-manifest.json
  app/build/images/Cart.svg
  app/build/images/Left.svg
  app/build/images/Minus.svg
  app/build/images/MyPage.svg
  app/build/images/Plus.svg
  app/build/images/Right.svg
  app/build/images/Search.svg
  app/build/index.html
  app/build/static/js/main.c0b141a3.js
  app/build/static/js/main.c0b141a3.js.LICENSE.txt
  app/build/static/js/main.c0b141a3.js.map
  app/public/images/Minus.svg
  app/public/images/Plus.svg
  app/src/components/App.js
  app/src/components/Card.js
  app/src/components/CardList.js
  app/src/components/Category.js
  app/src/components/Header.js
  app/src/components/MainTab.js
  app/src/components/Modal.js
  app/src/styles/theme.js
  app/src/styles/utils.js
Labels: review-FE

#100 [Team-14][FE] Jamie & 옐로우 1주차 두 번째 PR
  FE/fe-sidedish/.gitignore
  FE/fe-sidedish/package-lock.json
  FE/fe-sidedish/package.json
  FE/fe-sidedish/public/index.html
  FE/fe-sidedish/src/App.js
  FE/fe-sidedish/src/asset/icons/cart.svg
  FE/fe-sidedish/src/asset/icons/mypage.svg
  FE/fe-sidedish/src/asset/icons/search.svg
  FE/fe-sidedish/src/components/card/Badges.jsx
  FE/fe-sidedish/src/components/card/Card.jsx
  FE/fe-sidedish/src/components/card/Card.style.js
  FE/fe-sidedish/src/components/card/DeliveryBadge.jsx
  FE/fe-sidedish/src/components/card/Prices.jsx
  FE/fe-sidedish/src/components/card/SmallCard.jsx
  FE/fe-sidedish/src/components/category/Category.jsx
  FE/fe-sidedish/src/components/category/Category.style.js
  FE/fe-sidedish/src/components/exhibition/DishList.jsx
  FE/fe-sidedish/src/components/exhibition/Exhibition.jsx
  FE/fe-sidedish/src/components/exhibition/Exhibition.style.js
  FE/fe-sidedish/src/components/exhibition/ExhibitionTitle.jsx
  FE/fe-sidedish/src/components/exhibition/TabButton.jsx
  FE/fe-sidedish/src/components/exhibition/TapBar.jsx
  FE/fe-sidedish/src/components/header/Categories.jsx
  FE/fe-sidedish/src/components/header/Header.jsx
  FE/fe-sidedish/src/components/header/Header.style.js
  FE/fe-sidedish/src/components/header/HeaderTitle.jsx
  FE/fe-sidedish/src/components/header/IconMenu.jsx
  FE/fe-sidedish/src/components/header/IconMenuItems.jsx
  FE/fe-sidedish/src/components/header/Menus.jsx
  FE/fe-sidedish/src/components/header/NavigationItems.jsx
  FE/fe-sidedish/src/components/header/NavigationMenuItems.jsx
  FE/fe-sidedish/src/components/header/SubCategories.jsx
  FE/fe-sidedish/src/components/pages/Main.jsx
  FE/fe-sidedish/src/data/categories.js
  FE/fe-sidedish/src/data/dishes.js
  FE/fe-sidedish/src/data/iconMenus.js
  FE/fe-sidedish/src/data/nav.js
  FE/fe-sidedish/src/index.css
  FE/fe-sidedish/src/index.js
  FE/fe-sidedish/src/styles/GlobalStyle.jsx
  FE/fe-sidedish/src/styles/base/_font.scss
  FE/fe-sidedish/src/styles/base/_reset.scss
  FE/fe-sidedish/src/styles/base/_variables.scss
  FE/fe-sidedish/src/styles/base/app.scss
  FE/fe-sidedish/src/styles/components/card.scss
  FE/fe-sidedish/src/styles/components/header.scss
  FE/fe-sidedish/src/styles/theme.jsx
  FE/fe-sidedish/src/utils/index.js
Labels: review-FE

#112 [team-34][FE][JS&Geon] 1주차 금요일 PR
  front/src/App.js
  front/src/GlobalStyles.js
  front/src/components/Card.js
  front/src/components/Event.js
  front/src/components/Header.js
  front/src/components/Modal.js
  front/src/components/ProductDetail.js
  front/src/images/minus.svg
  front/src/images/plus.svg
  front/src/images/plusImg.svg
Labels: review-FE

#74 [team-04][BE] sidedish 1주차 두번째 PR #2
  BE/.gitignore
  BE/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
  BE/src/main/java/kr/codesquad/sidedish/controller/DishController.java
  BE/src/main/java/kr/codesquad/sidedish/controller/EventController.java
  BE/src/main/java/kr/codesquad/sidedish/controller/MainController.java
  BE/src/main/java/kr/codesquad/sidedish/domain/DeliveryType.java
  BE/src/main/java/kr/codesquad/sidedish/domain/DiscountPolicy.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Dish.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Event.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Image.java
  BE/src/main/java/kr/codesquad/sidedish/dto/CategorizedDishes.java
  BE/src/main/java/kr/codesquad/sidedish/dto/DishDetailResponse.java
  BE/src/main/java/kr/codesquad/sidedish/dto/DishSimpleResponse.java
  BE/src/main/java/kr/codesquad/sidedish/dto/SpecialEdition.java
  BE/src/main/java/kr/codesquad/sidedish/repository/JdbcDishRepository.java
  BE/src/main/java/kr/codesquad/sidedish/repository/JdbcEventRepository.java
  BE/src/main/java/kr/codesquad/sidedish/service/CategoryService.java
  BE/src/main/java/kr/codesquad/sidedish/service/DishService.java
  BE/src/main/java/kr/codesquad/sidedish/service/EventService.java
  BE/src/main/java/kr/codesquad/sidedish/service/MainService.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/kr/codesquad/sidedish/repository/JdbcCategoryRepositoryTest.java
  BE/src/test/java/kr/codesquad/sidedish/repository/JdbcDishRepositoryTest.java
Labels: review-BE

#59 [Team-03][BE][루이&쿠킴] - 특정 음식 타입 조회 기능
  BE/src/main/java/sidedish/com/controller/ProductsController.java
  BE/src/main/java/sidedish/com/controller/ProductsDtoMapper.java
  BE/src/main/java/sidedish/com/controller/model/ProductMealTypeResponse.java
  BE/src/main/java/sidedish/com/domain/DiscountPolicy.java
  BE/src/main/java/sidedish/com/domain/Image.java
  BE/src/main/java/sidedish/com/domain/Product.java
  BE/src/main/java/sidedish/com/exception/NoSuchProductsException.java
  BE/src/main/java/sidedish/com/repository/DiscountPolicyRepository.java
  BE/src/main/java/sidedish/com/repository/DomainEntityMapper.java
  BE/src/main/java/sidedish/com/repository/ProductsRepository.java
  BE/src/main/java/sidedish/com/repository/entity/DiscountPolicyEntity.java
  BE/src/main/java/sidedish/com/repository/entity/ImageEntity.java
  BE/src/main/java/sidedish/com/repository/entity/ProductEntity.java
  BE/src/main/java/sidedish/com/service/ProductsService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/sidedish/com/ComApplicationTests.java
  BE/src/test/java/sidedish/com/acceptancetest/ProductsAcceptanceTest.java
  BE/src/test/java/sidedish/com/controller/ProductsControllerTest.java
  BE/src/test/java/sidedish/com/domain/ProductTest.java
  BE/src/test/java/sidedish/com/repository/ProductsRepositoryTest.java
  BE/src/test/resources/application.yml
  BE/src/test/resources/testdb/data.sql
  BE/src/test/resources/testdb/schema.sql
Labels: review-BE

#107 [team-33 sonya & 난정] 1주차 금요일 PR
  frontend/sidedish/package-lock.json
  frontend/sidedish/package.json
  frontend/sidedish/public/global.css
  frontend/sidedish/public/index.html
  frontend/sidedish/public/reset.css
  frontend/sidedish/src/App.css
  frontend/sidedish/src/App.js
  frontend/sidedish/src/BigSidedish.css
  frontend/sidedish/src/BigSidedish.js
  frontend/sidedish/src/Header.css
  frontend/sidedish/src/Header.js
  frontend/sidedish/src/index.css
  frontend/sidedish/src/index.js
Labels: review-FE

#85 [team-26] [Android] SideDish Project PR2 - 피드백 적용 및 api 연동
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/codesquadhan/sidedish/SideDishApplication.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/data/model/DetailImage.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/data/model/MenuData.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/data/model/be/MainResponse.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/data/model/be/MainResponseItem.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/data/model/onban/OnbanBody.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/data/model/onban/OnbanMainResponse.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/data/repository/MenuRepository.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/di/NetworkModule.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/network/MenuService.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/constant/ViewType.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/detail/DetailAdapter.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/detail/DetailViewModel.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/main/MainActivity.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/main/MainAdapter.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/main/MainViewModel.kt
  Android/app/src/main/res/layout/activity_detail.xml
  Android/app/src/main/res/layout/item_detail.xml
  Android/app/src/main/res/layout/item_main_food.xml
  Android/app/src/main/res/layout/item_main_header.xml
Labels: review-android

#104 [Team-18 iOS] Eddy&Kai 수요일 피드백 적용 및 viewModel 구현
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp/Common/Extension.swift
  SideDishApp/SideDishApp/Common/Obseverable.swift
  SideDishApp/SideDishApp/Common/SystemLog.swift
  SideDishApp/SideDishApp/Model/Badge.swift
  SideDishApp/SideDishApp/Model/Category.swift
  SideDishApp/SideDishApp/Model/Delivery.swift
  SideDishApp/SideDishApp/Model/DetailData.swift
  SideDishApp/SideDishApp/Model/Money.swift
  SideDishApp/SideDishApp/Model/MoneyCurrency.swift
  SideDishApp/SideDishApp/Model/Product.swift
  SideDishApp/SideDishApp/Model/ProductDetail.swift
  SideDishApp/SideDishApp/Model/ProductType.swift
  SideDishApp/SideDishApp/Networking/NetworkManager.swift
  SideDishApp/SideDishApp/Resource/Assets.xcassets/1155_ZIP_P_0081_T.imageset/Contents.json
  SideDishApp/SideDishApp/Resource/Assets.xcassets/1155_ZIP_P_0081_T.imageset/testImage0081.jpg
  SideDishApp/SideDishApp/Service/CategoryManager.swift
  SideDishApp/SideDishApp/View/Base.lproj/Main.storyboard
  SideDishApp/SideDishApp/View/MainCollectionViewCell.swift
  SideDishApp/SideDishApp/View/MainCollectionViewCell.xib
  SideDishApp/SideDishApp/View/MainCollectionViewSectionHeader.swift
  SideDishApp/SideDishApp/View/MainViewController.swift
  SideDishApp/SideDishApp/View/ViewController.swift
  SideDishApp/SideDishApp/ViewModel/ProductCellViewModel.swift
  SideDishApp/SideDishApp/ViewModel/ProductCollectionViewModel.swift
  SideDishApp/SideDishAppTests/CategoryManagerTests.swift
  SideDishApp/SideDishAppTests/NetworkManagerTests.swift
  SideDishApp/SideDishAppTests/ProductCollectionViewModelTests.swift
  SideDishApp/SideDishAppTests/ProductDecodingTests.swift
  SideDishApp/SideDishAppTests/ProductDetailDecodingTest.swift
Labels: review-iOS

#103 [Team-22][iOS] 1주차-2: 컬렉션 뷰 적용, 리팩토링
  SideDish/SideDish.xcodeproj/project.pbxproj
  SideDish/SideDish/Assets.xcassets/AppIcon.appiconset/Contents.json
  SideDish/SideDish/Base.lproj/Main.storyboard
  SideDish/SideDish/Commmon/JSONHandlable.swift
  SideDish/SideDish/Commmon/JSONHandler.swift
  SideDish/SideDish/Controllers/MainViewController.swift
  SideDish/SideDish/Controllers/ViewController.swift
  SideDish/SideDish/Model+Repository/Category.swift
  SideDish/SideDish/Model+Repository/Food.swift
  SideDish/SideDish/Model+Repository/Mock/MockRepository.swift
  SideDish/SideDish/Model+Repository/Ordering.swift
  SideDish/SideDish/Model+Repository/Repository.swift
  SideDish/SideDish/Model+Repository/RepositoryApplicable.swift
  SideDish/SideDish/Model+Repository/RepositoryDelegate.swift
  SideDish/SideDish/Model+Repository/Response.swift
  SideDish/SideDish/Model/Ordering.swift
  SideDish/SideDish/Model/Response.swift
  SideDish/SideDish/SceneDelegate.swift
  SideDish/SideDish/Supportings/AppDelegate.swift
  SideDish/SideDish/Supportings/SceneDelegate.swift
  SideDish/SideDish/Views/FoodCollectionViewCell.swift
  SideDish/SideDishTests/FoodTest.swift
  SideDish/SideDishTests/JSONHandlerTest.swift
  SideDish/SideDishTests/OrderingTest.swift
Labels: review-iOS

#96 [Team-27] Android 힐트 라이브러리 적용 및 피드백 반영
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/sidedish/data/DataSource.kt
  android/app/src/main/java/com/example/sidedish/data/Food.kt
  android/app/src/main/java/com/example/sidedish/data/MenuListDataSource.kt
  android/app/src/main/java/com/example/sidedish/data/MenuListRepository.kt
  android/app/src/main/java/com/example/sidedish/di/MainApplication.kt
  android/app/src/main/java/com/example/sidedish/di/Module.kt
  android/app/src/main/java/com/example/sidedish/network/ApiClient.kt
  android/app/src/main/java/com/example/sidedish/ui/HomeActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/MainActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/MainMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/MenuItemClickListener.kt
  android/app/src/main/java/com/example/sidedish/ui/MenuListViewModel.kt
  android/app/src/main/java/com/example/sidedish/ui/SideMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/SoupMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/adapter/ImageViewPagerAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/adapter/MenuListAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/detail/MenuDetailFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/HomeActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/HomeFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/MainMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/MenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/SideMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/SoupMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/viewmodel/MenuListViewModel.kt
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_main.xml
  android/app/src/main/res/layout/fragment_side.xml
  android/app/src/main/res/layout/fragment_soup.xml
  android/app/src/main/res/layout/item_menu_list.xml
  android/app/src/main/res/layout/item_thumbnail.xml
  android/app/src/main/res/navigation/nav_graph.xml
  android/build.gradle
Labels: review-android

#110 [Android] team-28 - MainProduct Hilt 적용 및 ProductDetail UI 완성
  android/.idea/deploymentTargetDropDown.xml
  android/.idea/misc.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/product_detail.json
  android/app/src/main/java/com/example/sidedish/ApiService.kt
  android/app/src/main/java/com/example/sidedish/AppModule.kt
  android/app/src/main/java/com/example/sidedish/BindingAdapter.kt
  android/app/src/main/java/com/example/sidedish/GlideModule.kt
  android/app/src/main/java/com/example/sidedish/HiltApplication.kt
  android/app/src/main/java/com/example/sidedish/MainActivity.kt
  android/app/src/main/java/com/example/sidedish/MainHomeAdapter.kt
  android/app/src/main/java/com/example/sidedish/MainViewModel.kt
  android/app/src/main/java/com/example/sidedish/MenuList.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailActivity.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailDataSource.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailImage.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailImageAdapter.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailImageDataSource.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailRepository.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailTitleImage.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailViewModel.kt
  android/app/src/main/java/com/example/sidedish/Products.kt
  android/app/src/main/java/com/example/sidedish/Repository.kt
  android/app/src/main/java/com/example/sidedish/ViewModelFactory.kt
  android/app/src/main/res/drawable/badge_background.xml
  android/app/src/main/res/drawable/bg_event_badge.xml
  android/app/src/main/res/drawable/count_background.xml
  android/app/src/main/res/drawable/edge.xml
  android/app/src/main/res/drawable/ic_baseline_add_42.xml
  android/app/src/main/res/drawable/ic_baseline_remove_42.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/activity_product_detail.xml
  android/app/src/main/res/layout/item_menu_data.xml
  android/app/src/main/res/layout/item_porduct_detail_image.xml
  android/app/src/main/res/values-night/strings.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: review-android

#65 [team-10][FE][이든, Khan] 반찬가게 Step2
  public/data/mainCard.json
  public/data/mainDish.json
  public/data/sideDish.json
  public/data/soup.json
  public/index.html
  src/App.js
  src/Header.js
  src/MainCard.js
  src/SubCard.js
  src/components/Button.js
  src/components/Card.js
  src/components/CategoryTitle.js
  src/components/Gnb.js
  src/components/GnbItem.js
  src/components/Infos.js
  src/components/Menu.js
  src/components/Tab.js
  src/container/CardContainer.js
  src/css/variables.js
  src/index.js
Labels: review-FE

#77 [team-25][iOS] 1주차 금요일 PR입니다.
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject/DetailViewController.swift
  SideDishProject/SideDishProject/DishCollectionViewCell.swift
  SideDishProject/SideDishProject/DishCollectionWrapper.swift
  SideDishProject/SideDishProject/DishCommetHeaderView.swift
  SideDishProject/SideDishProject/HomeView.swift
  SideDishProject/SideDishProject/HomeViewController.swift
  SideDishProject/SideDishProject/MockProductFactory.swift
  SideDishProject/SideDishProject/Product.swift
  SideDishProject/SideDishProject/ProductModel.swift
  SideDishProject/SideDishProject/ProductRepository.swift
  SideDishProject/SideDishProject/ProductSceneContainer.swift
  SideDishProject/SideDishProject/RootNavigationController.swift
  SideDishProject/SideDishProject/SceneDelegate.swift
Labels: review-iOS

#115 [Team-13][BE] 기획 목록 조회 기능 구현
  backend/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
  backend/src/main/java/kr/codesquad/sidedish/controller/ThemeController.java
  backend/src/main/java/kr/codesquad/sidedish/controller/dto/CategoryListResponse.java
  backend/src/main/java/kr/codesquad/sidedish/controller/dto/ThemeListResponse.java
  backend/src/main/java/kr/codesquad/sidedish/domain/Theme.java
  backend/src/main/java/kr/codesquad/sidedish/repository/CategoryRepository.java
  backend/src/main/java/kr/codesquad/sidedish/repository/ThemeRepository.java
  backend/src/main/java/kr/codesquad/sidedish/service/CategoryService.java
  backend/src/main/java/kr/codesquad/sidedish/service/ThemeService.java
  backend/src/main/resources/sql/data.sql
  backend/src/test/java/kr/codesquad/sidedish/service/CategoryServiceTest.java
Labels: review-BE

#73 [team-02][BE][Phill & Hanse] sidedish 1주차 PR#2
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/runConfigurations/SidedishApplication.xml
  .idea/uiDesigner.xml
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/sidedish/domain/Image.java
  backend/src/main/java/com/sidedish/domain/product/EventBadge.java
  backend/src/main/java/com/sidedish/domain/product/EventCategory.java
  backend/src/main/java/com/sidedish/domain/product/MainCategory.java
  backend/src/main/java/com/sidedish/domain/product/Product.java
  backend/src/main/java/com/sidedish/domain/product/ProductOrder.java
  backend/src/main/java/com/sidedish/domain/user/User.java
  backend/src/main/java/com/sidedish/repository/ProductRepository.java
  backend/src/main/java/com/sidedish/servcie/ProductService.java
  backend/src/main/java/com/sidedish/web/controller/ProductController.java
  backend/src/main/java/com/sidedish/web/dto/MainCategoryProductDto.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: review-BE

#62 [TEAM-24] [땃쥐, Lee] BE 두번째 PR입니다.
  BE/src/main/java/codesquad/sidedish/domain/address/Address.java
  BE/src/main/java/codesquad/sidedish/domain/address/District.java
  BE/src/main/java/codesquad/sidedish/domain/delivery/Delivery.java
  BE/src/main/java/codesquad/sidedish/domain/delivery/DeliveryType.java
  BE/src/main/java/codesquad/sidedish/domain/discount/DiscountPolicy.java
  BE/src/main/java/codesquad/sidedish/domain/member/Member.java
  BE/src/main/java/codesquad/sidedish/domain/member/MemberRepository.java
  BE/src/main/java/codesquad/sidedish/web/controller/ItemController.java
  BE/src/main/java/codesquad/sidedish/web/controller/OrderController.java
  BE/src/main/java/codesquad/sidedish/web/controller/TestController.java
  BE/src/main/java/codesquad/sidedish/web/dto/ItemDetailResponse.java
  BE/src/main/java/codesquad/sidedish/web/dto/ItemListElement.java
  BE/src/main/java/codesquad/sidedish/web/dto/ItemListResponse.java
  BE/src/main/java/codesquad/sidedish/web/dto/OrderCreateRequest.java
  BE/src/main/java/codesquad/sidedish/web/dto/OrderCreateResponse.java
  BE/src/main/resources/schema.sql
  BE/src/test/java/codesquad/sidedish/domain/discount/DiscountPolicyTest.java
  BE/src/test/java/codesquad/sidedish/domain/member/MemberRepositoryTest.java
  BE/src/test/java/codesquad/sidedish/domain/member/MemberTest.java
Labels: review-BE

#88 [Team-30][Android] 메뉴 아이템 상세보기 및 주문 완료 및 취소 다이얼로그
  app/build.gradle
  app/src/main/java/com/example/todo/sidedish/data/dto/MenuDetailDto.kt
  app/src/main/java/com/example/todo/sidedish/data/remote/DataSource.kt
  app/src/main/java/com/example/todo/sidedish/data/remote/OnBanApi.kt
  app/src/main/java/com/example/todo/sidedish/data/remote/OnBanDataSource.kt
  app/src/main/java/com/example/todo/sidedish/data/repository/MenuRepositoryImpl.kt
  app/src/main/java/com/example/todo/sidedish/domain/Repository.kt
  app/src/main/java/com/example/todo/sidedish/domain/model/MenuDetail.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuAdapter.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuViewModel.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/MenuDetailAdapter.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/MenuDetailFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/MenuDetailViewModel.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/OrderCancelDialogFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/OrderCompleteDialogFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/ViewPagerAdapter.kt
  app/src/main/res/drawable-v24/background_white.xml
  app/src/main/res/drawable/ic_add_order.xml
  app/src/main/res/drawable/ic_sub_order.xml
  app/src/main/res/layout/fragment_menu_detail.xml
  app/src/main/res/layout/fragment_order_cancel_dialog.xml
  app/src/main/res/layout/fragment_order_complete_dialog.xml
  app/src/main/res/layout/item_detail_image.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/layout/item_viepager.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: review-android

#86 [Team-29][Android] 피드백 반영 및 상세 화면 수정
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sideDish/MainActivity.kt
  app/src/main/java/com/example/sideDish/common/ViewModelFactory.kt
  app/src/main/java/com/example/sideDish/data/FoodCategory.kt
  app/src/main/java/com/example/sideDish/data/source/FoodDetail.kt
  app/src/main/java/com/example/sideDish/data/source/FoodRepository.kt
  app/src/main/java/com/example/sideDish/ui/BindingAdapters.kt
  app/src/main/java/com/example/sideDish/ui/Stepper.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListAdapter.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListFragment.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListViewModel.kt
  app/src/main/java/com/example/sideDish/ui/productdetail/FoodDetailViewModel.kt
  app/src/main/java/com/example/sideDish/ui/productdetail/ProductDetailFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/section.xml
  app/src/main/res/layout/stepper.xml
  app/src/main/res/values/strings.xml
Labels: review-android

#162 [Team 09] [dony, 럼카] 2주차 1번째 PR 요청드립니다.
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/GlobalStyles.js
  src/Sidedish.jsx
  src/components/Button.jsx
  src/components/Header.jsx
  src/components/Header/GNB.jsx
  src/components/Header/Header.jsx
  src/components/Header/Logo.jsx
  src/components/Header/MyUtils.jsx
  src/components/Header/SubGNB.jsx
  src/components/IconButton.jsx
  src/components/MainCategory/Contents.jsx
  src/components/MainCategory/MainCategory.jsx
  src/components/MainCategory/Tab/TabBar.jsx
  src/components/MainCategory/Tab/TabButton.jsx
  src/components/MenuSection/MenuSection.jsx
  src/components/MenuSection/MenuSlider.jsx
  src/components/MenuSection/slideMockData.js
  src/components/MoreButton.jsx
  src/components/TabBar.jsx
  src/components/Text.jsx
  src/components/common/Button.jsx
  src/components/common/Card/Card.jsx
  src/components/common/Card/Tag.jsx
  src/components/common/IconButton.jsx
  src/components/utils/Text.jsx
  src/index.jsx
  src/template/Template.jsx
  src/variable/color.js
  src/variable/font.js
  src/variable/theme.js
Labels: review-FE

#141 [team-13] Alan & Inu 수요일의 PR
  README.md
  frontend/README.md
  frontend/package-lock.json
  frontend/public/mocks/categoryProducts.json
  frontend/public/mocks/product.json
  frontend/public/mocks/specialCategoryProducts.json
  frontend/src/App.js
  frontend/src/ModalReducer.js
  frontend/src/components/BestProduct.js
  frontend/src/components/Button.js
  frontend/src/components/CardList.js
  frontend/src/components/Carousel.js
  frontend/src/components/Category.js
  frontend/src/components/DiscountTag.js
  frontend/src/components/Gnb.js
  frontend/src/components/GnbMenu.js
  frontend/src/components/Header.js
  frontend/src/components/HorizontalLine.js
  frontend/src/components/Modal.js
  frontend/src/components/ProductCard.js
  frontend/src/components/SpecialCategory.js
  frontend/src/convention.js
  frontend/src/fetcher.js
  frontend/src/icons/EventBadge.js
  frontend/src/icons/LeftArrowIcon.js
  frontend/src/icons/Logo.js
  frontend/src/icons/PlusMinus.js
  frontend/src/icons/RightArrowIcon.js
  frontend/src/icons/headerIcons.js
  frontend/src/index.js
  frontend/src/styles/global.js
  frontend/src/styles/theme.js
  package.json
  yarn.lock
Labels: review-FE

#136 [Team-12 BE] 2주차 첫번째 PR (2022/4/27)
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/src/docs/asciidoc/index.adoc
  BE/src/main/java/com/sidedish/api/categories/CategoryController.java
  BE/src/main/java/com/sidedish/api/categories/DetailController.java
  BE/src/main/java/com/sidedish/api/categories/dto/ItemResource.java
  BE/src/main/java/com/sidedish/api/categories/dto/ResponseItemDto.java
  BE/src/main/java/com/sidedish/api/categories/initDB.java
  BE/src/main/java/com/sidedish/api/common/ExceptionAdvice.java
  BE/src/main/java/com/sidedish/api/common/ResultDto.java
  BE/src/main/java/com/sidedish/api/home/HomeController.java
  BE/src/main/java/com/sidedish/api/home/ResponseAdditionalDto.java
  BE/src/main/java/com/sidedish/api/home/dto/ResponseHomeDto.java
  BE/src/main/java/com/sidedish/api/order/OrderController.java
  BE/src/main/java/com/sidedish/api/order/dto/OrderRequest.java
  BE/src/main/java/com/sidedish/config/WebMvcConfig.java
  BE/src/main/java/com/sidedish/domain/CategoryType.java
  BE/src/main/java/com/sidedish/domain/Item.java
  BE/src/main/java/com/sidedish/exception/QuantityException.java
  BE/src/main/java/com/sidedish/repository/CategoryRepository.java
  BE/src/main/java/com/sidedish/repository/ItemRepository.java
  BE/src/main/java/com/sidedish/service/ItemService.java
  BE/src/main/java/com/sidedish/service/OrderService.java
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/data/data.sql
  BE/src/main/resources/data/schema.sql
  BE/src/test/java/com/sidedish/SidedishApplicationTests.java
  BE/src/test/java/com/sidedish/api/categories/CategoryIntegrationTest.java
  BE/src/test/resources/application-test.yml
Labels: review-BE

#131 [BE][Team-26] 2주차 1차 PR
  BE/build.gradle
  BE/src/main/java/sidedish/jbc/config/WebConfig.java
  BE/src/main/java/sidedish/jbc/controller/MenuController.java
  BE/src/main/java/sidedish/jbc/controller/OAuthController.java
  BE/src/main/java/sidedish/jbc/domain/Image.java
  BE/src/main/java/sidedish/jbc/domain/Menu.java
  BE/src/main/java/sidedish/jbc/domain/MenuOrder.java
  BE/src/main/java/sidedish/jbc/domain/MenuType.java
  BE/src/main/java/sidedish/jbc/domain/OauthDto.java
  BE/src/main/java/sidedish/jbc/domain/SaleType.java
  BE/src/main/java/sidedish/jbc/domain/User.java
  BE/src/main/java/sidedish/jbc/dto/DetailMenu.java
  BE/src/main/java/sidedish/jbc/dto/DetailMenuImages.java
  BE/src/main/java/sidedish/jbc/dto/DetailMenuResponse.java
  BE/src/main/java/sidedish/jbc/dto/MenuOrderResponse.java
  BE/src/main/java/sidedish/jbc/dto/MenuResponse.java
  BE/src/main/java/sidedish/jbc/dto/OrderRequest.java
  BE/src/main/java/sidedish/jbc/interceptor/LoginCheckInterceptor.java
  BE/src/main/java/sidedish/jbc/repository/ImageRepository.java
  BE/src/main/java/sidedish/jbc/repository/MenuRepository.java
  BE/src/main/java/sidedish/jbc/repository/UserRepository.java
  BE/src/main/java/sidedish/jbc/service/MenuService.java
  BE/src/main/java/sidedish/jbc/service/OrderService.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-BE

#140 [team-8][FE] 베니 & 포키 2주차 첫번째 PR
  README.md
  app/public/images/Arrow.svg
  app/public/images/ModalCarouselLeft.svg
  app/public/images/ModalCarouselRight.svg
  app/src/components/App.js
  app/src/components/Card.js
  app/src/components/CardList.js
  app/src/components/Category.js
  app/src/components/MainTab.js
  app/src/components/Modal.js
  app/src/components/Modal/Alert.js
  app/src/components/Modal/Carousel.js
  app/src/components/Modal/Modal.js
  app/src/components/Modal/Product.js
  app/src/components/Slider.js
  app/src/contexts/ModalContext.js
  app/src/index.js
  app/src/styles/Modal/Alert.js
  app/src/styles/Modal/Carousel.js
  app/src/styles/Modal/Modal.js
  app/src/styles/Modal/Product.js
  app/src/styles/theme.js
  app/src/styles/utils.js
Labels: review-FE

#170 [Team-5 FE BB & JinJeon] Sidedish 프로젝트 2주차(수요일) PR
  fe/jsconfig.json
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/public/robots.txt
  fe/src/App.jsx
  fe/src/Component/Card/Card.jsx
  fe/src/Component/Card/Card.styled.js
  fe/src/Component/Card/CardDiscountType.jsx
  fe/src/Component/Card/CardImageAndFlag.jsx
  fe/src/Component/Card/CardPrice.jsx
  fe/src/Component/Header/Header.jsx
  fe/src/Component/Header/Header.styled.js
  fe/src/Component/Header/HeaderLeft/HeaderLeft.jsx
  fe/src/Component/Header/HeaderLeft/Menu.Styled.js
  fe/src/Component/Header/HeaderLeft/Menu.jsx
  fe/src/Component/Header/HeaderLeft/Nav.jsx
  fe/src/Component/Header/HeaderLeft/Nav.styled.js
  fe/src/Component/Header/HeaderRight/HeaderRight.jsx
  fe/src/Component/Main/EventArea/EventArea.jsx
  fe/src/Component/Main/EventArea/EventArea.styled.js
  fe/src/Component/Main/EventArea/EventContents/EventContents.jsx
  fe/src/Component/Main/EventArea/EventTab/EventTab.jsx
  fe/src/Component/Main/EventArea/EventTab/EventTab.styled.js
  fe/src/Component/Main/Main.jsx
  fe/src/Component/Main/RestCategoriesArea/BtnShowAndHideArea.jsx
  fe/src/Component/Main/RestCategoriesArea/RestCategoriesArea.jsx
  fe/src/Component/Main/SideDishItemsArea/Category/Category.jsx
  fe/src/Component/Main/SideDishItemsArea/Category/Category.styled.js
  fe/src/Component/Main/SideDishItemsArea/Category/ImgSlider/ImgSlider.jsx
  fe/src/Component/Main/SideDishItemsArea/Category/ImgSlider/ImgSlider.styled.js
  fe/src/Component/Main/SideDishItemsArea/Category/ImgSlider/SliderButton.jsx
  fe/src/Component/Main/SideDishItemsArea/Category/ImgSlider/SliderButton.styled.js
  fe/src/Component/Main/SideDishItemsArea/SideDishItemsArea.jsx
  fe/src/MockData/MockData.jsx
  fe/src/MockData/browsers.js
  fe/src/MockData/handlers.js
  fe/src/Service/eventCategoriesApi.js
  fe/src/Service/menuCategoriesApi.js
  fe/src/Styles/Normalize.js
  fe/src/Styles/Reset.js
  fe/src/Styles/theme.js
  fe/src/index.jsx
Labels: review-FE

#159 [team28 - Backend] 코드리뷰 피드백 적용 및 실제 API 구현완료
  backend/src/main/java/com/team28/sidedish/controller/OrderController.java
  backend/src/main/java/com/team28/sidedish/controller/ProductController.java
  backend/src/main/java/com/team28/sidedish/controller/dto/CategoryResponse.java
  backend/src/main/java/com/team28/sidedish/controller/dto/OrderRequest.java
  backend/src/main/java/com/team28/sidedish/controller/dto/ProductDetailResponse.java
  backend/src/main/java/com/team28/sidedish/controller/dto/ProductImageResponse.java
  backend/src/main/java/com/team28/sidedish/controller/dto/ProductListResponse.java
  backend/src/main/java/com/team28/sidedish/controller/dto/ProductResponse.java
  backend/src/main/java/com/team28/sidedish/domain/Product.java
  backend/src/main/java/com/team28/sidedish/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/team28/sidedish/exception/OutOfStockException.java
  backend/src/main/java/com/team28/sidedish/exception/ProductNotFoundException.java
  backend/src/main/java/com/team28/sidedish/exception/SidedishRuntimeException.java
  backend/src/main/java/com/team28/sidedish/repository/CategoryRepository.java
  backend/src/main/java/com/team28/sidedish/repository/DiscountRepository.java
  backend/src/main/java/com/team28/sidedish/repository/MemberRepository.java
  backend/src/main/java/com/team28/sidedish/repository/OrderProductsRepository.java
  backend/src/main/java/com/team28/sidedish/repository/OrdersRepository.java
  backend/src/main/java/com/team28/sidedish/repository/ProductImageRepository.java
  backend/src/main/java/com/team28/sidedish/repository/ProductRepository.java
  backend/src/main/java/com/team28/sidedish/repository/entity/CategoryEntity.java
  backend/src/main/java/com/team28/sidedish/repository/entity/DiscountEntity.java
  backend/src/main/java/com/team28/sidedish/repository/entity/MemberEntity.java
  backend/src/main/java/com/team28/sidedish/repository/entity/OrderProductsEntity.java
  backend/src/main/java/com/team28/sidedish/repository/entity/OrdersEntity.java
  backend/src/main/java/com/team28/sidedish/repository/entity/ProductEntity.java
  backend/src/main/java/com/team28/sidedish/repository/entity/ProductImageEntity.java
  backend/src/main/java/com/team28/sidedish/service/CategoryService.java
  backend/src/main/java/com/team28/sidedish/service/DiscountService.java
  backend/src/main/java/com/team28/sidedish/service/MockProductImageService.java
  backend/src/main/java/com/team28/sidedish/service/OrderService.java
  backend/src/main/java/com/team28/sidedish/service/ProductDiscountService.java
  backend/src/main/java/com/team28/sidedish/service/ProductService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/schema.sql
Labels: review-BE

#164 [team-31][FE] 아울 & 올리버 2주차 첫 번째 PR
  frontend/sidedish/public/carouselMockData.json
  frontend/sidedish/public/images/cartIcon.png
  frontend/sidedish/public/images/cartIcon.svg
  frontend/sidedish/public/images/leftIcon.svg
  frontend/sidedish/public/images/rightIcon.svg
  frontend/sidedish/public/images/searchIcon.png
  frontend/sidedish/public/images/searchIcon.svg
  frontend/sidedish/public/images/userIcon.png
  frontend/sidedish/public/images/userIcon.svg
  frontend/sidedish/src/App.jsx
  frontend/sidedish/src/asset/cartIcon.svg
  frontend/sidedish/src/asset/leftIcon.svg
  frontend/sidedish/src/asset/rightIcon.svg
  frontend/sidedish/src/asset/searchIcon.svg
  frontend/sidedish/src/asset/userIcon.svg
  frontend/sidedish/src/carouselMockData.json
  frontend/sidedish/src/components/Carousel.jsx
  frontend/sidedish/src/components/ItemCards.jsx
  frontend/sidedish/src/components/Main.jsx
  frontend/sidedish/src/components/header/Gnb.jsx
  frontend/sidedish/src/components/header/Header.jsx
  frontend/sidedish/src/components/header/MenuTypeList.jsx
  frontend/sidedish/src/components/itemCard/ItemCard.jsx
  frontend/sidedish/src/components/itemCard/ItemCards.jsx
  frontend/sidedish/src/components/main/Carousel.jsx
  frontend/sidedish/src/components/main/Main.jsx
  frontend/sidedish/src/components/popup/OrderBtn.jsx
  frontend/sidedish/src/components/popup/OrderDetail.jsx
  frontend/sidedish/src/components/popup/OrderNumber.jsx
  frontend/sidedish/src/components/popup/Popup.jsx
  frontend/sidedish/src/components/popup/PopupDetail.jsx
  frontend/sidedish/src/components/popup/PopupImageContents.jsx
  frontend/sidedish/src/components/popup/PopupOrderContents.jsx
  frontend/sidedish/src/components/popup/RelatedContents.jsx
  frontend/sidedish/src/components/popup/RelatedLists.jsx
  frontend/sidedish/src/consts/constants.js
  frontend/sidedish/src/core/Blank.jsx
  frontend/sidedish/src/core/Label.jsx
  frontend/sidedish/src/core/LeftArrowBtn.jsx
  frontend/sidedish/src/core/MinusBtn.jsx
  frontend/sidedish/src/core/PlusBtn.jsx
  frontend/sidedish/src/core/RightArrowBtn.jsx
  frontend/sidedish/src/mockData.json
  frontend/sidedish/src/relatedListMockData.json
  frontend/sidedish/src/util/fetchData.js
  frontend/sidedish/src/util/makePriceFormat.js
Labels: review-FE

#147 [team-35] [bangtae & 호이] 2주차 첫번째 PR
  fe/src/App.js
  fe/src/components/Card.js
  fe/src/components/Card.styled.js
  fe/src/components/productCard/ProductCard.js
  fe/src/components/productCard/ProductCard.styled.js
  fe/src/components/productCard/deliveryCircle/deliveryCircle.js
  fe/src/components/productCard/deliveryCircle/deliveryCircle.styled.js
  fe/src/components/productCard/eventWrapper/eventWrapper.js
  fe/src/components/productCard/eventWrapper/eventWrapper.styled.js
  fe/src/helper/constants.js
  fe/src/helper/mock.js
  fe/src/helper/mock.json
  fe/src/helper/utils.js
  fe/src/views/BestProduct.js
  fe/src/views/bestProduct/BestProduct.styled.js
  fe/src/views/bestProduct/tabList.js
  fe/src/views/bestProduct/tabMenu.js
  fe/src/views/header/Header.js
  fe/src/views/header/Header.styled.js
  fe/src/views/header/gnbLists/gnbLists.js
  fe/src/views/header/gnbLists/gnbLists.styled.js
  fe/src/views/header/svg.js
  fe/src/views/header/svg/svg.js
  fe/src/views/header/svg/svg.styled.js
  fe/src/views/main/bestProduct/BestProduct.js
  fe/src/views/main/bestProduct/BestProduct.styled.js
  fe/src/views/main/bestProduct/tabList/tabList.js
  fe/src/views/main/bestProduct/tabList/tabList.styled.js
  fe/src/views/main/bestProduct/tabMenu/tabMenu.js
  fe/src/views/main/bestProduct/tabMenu/tabMenu.styled.js
  fe/src/views/main/bestProduct/title/exhibitionTitle.js
  fe/src/views/main/bestProduct/title/exhibitionTitle.styled.js
  fe/src/views/main/categoryArea/CategoryArea.js
  fe/src/views/main/categoryArea/category/category.js
  fe/src/views/main/categoryArea/category/category.styled.js
  fe/src/views/main/categoryArea/category/extendBtn.js
Labels: review-FE

#126 [team-04][FE] 도비 & Muffin PR 2주차 수 PR
  fe/.env
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.jsx
  fe/src/Callback.jsx
  fe/src/Header/HeaderCategory.jsx
  fe/src/Header/HeaderLogin.jsx
  fe/src/Header/HeaderTemplate.jsx
  fe/src/Home.jsx
  fe/src/Main/Card.jsx
  fe/src/Main/CardDeliveryInfo.jsx
  fe/src/Main/Dish/DishCategoryAllButton.jsx
  fe/src/Main/Dish/DishContainer.jsx
  fe/src/Main/Dish/DishTogatherContainer.jsx
  fe/src/Main/MainContainer.jsx
  fe/src/Main/Recommend/RecommendProduct.jsx
  fe/src/Main/Recommend/RecommendTab.jsx
  fe/src/Main/Recommend/RecommendTabList.jsx
  fe/src/MockData/dummyData.js
  fe/src/Modal/ModalDetailContainer.jsx
  fe/src/Modal/ModalImgWrapper.jsx
  fe/src/Modal/index.jsx
  fe/src/common/Error.jsx
  fe/src/common/FlexDiv.jsx
  fe/src/common/Loading.jsx
  fe/src/constant.js
  fe/src/image/loading.gif
  fe/src/index.js
  fe/src/theme.jsx
Labels: review-FE

#158 [Team-14][FE] Jamie & 옐로우 2주차 첫 번째 PR
  FE/fe-sidedish/.prettierrc
  FE/fe-sidedish/public/index.html
  FE/fe-sidedish/src/asset/icons/minus.svg
  FE/fe-sidedish/src/asset/icons/plus.svg
  FE/fe-sidedish/src/components/card/Badges.jsx
  FE/fe-sidedish/src/components/card/Card.jsx
  FE/fe-sidedish/src/components/card/Card.style.js
  FE/fe-sidedish/src/components/card/DeliveryBadge.jsx
  FE/fe-sidedish/src/components/card/Prices.jsx
  FE/fe-sidedish/src/components/card/SmallCard.jsx
  FE/fe-sidedish/src/components/category/Category.jsx
  FE/fe-sidedish/src/components/category/Category.style.js
  FE/fe-sidedish/src/components/exhibition/DishList.jsx
  FE/fe-sidedish/src/components/exhibition/Exhibition.jsx
  FE/fe-sidedish/src/components/exhibition/Exhibition.style.js
  FE/fe-sidedish/src/components/exhibition/ExhibitionMenus.jsx
  FE/fe-sidedish/src/components/exhibition/ExhibitionTitle.jsx
  FE/fe-sidedish/src/components/exhibition/TabButton.jsx
  FE/fe-sidedish/src/components/exhibition/TapBar.jsx
  FE/fe-sidedish/src/components/header/Header.jsx
  FE/fe-sidedish/src/components/header/Header.style.js
  FE/fe-sidedish/src/components/header/HeaderCategories.jsx
  FE/fe-sidedish/src/components/header/HeaderTitle.jsx
  FE/fe-sidedish/src/components/header/IconMenuItems.jsx
  FE/fe-sidedish/src/components/header/IconMenus.jsx
  FE/fe-sidedish/src/components/header/NavigationItems.jsx
  FE/fe-sidedish/src/components/header/NavigationMenuItems.jsx
  FE/fe-sidedish/src/components/modal/AlertModal.js
  FE/fe-sidedish/src/components/modal/Modal.style.js
  FE/fe-sidedish/src/components/pages/Main.jsx
  FE/fe-sidedish/src/components/portal/Portal.jsx
  FE/fe-sidedish/src/components/portal/Portal.style.js
  FE/fe-sidedish/src/components/productDetailModal/Badges.jsx
  FE/fe-sidedish/src/components/productDetailModal/CostItem.jsx
  FE/fe-sidedish/src/components/productDetailModal/IconButton.jsx
  FE/fe-sidedish/src/components/productDetailModal/ProductDetailModal.jsx
  FE/fe-sidedish/src/components/productDetailModal/ProductDetailModal.style.js
  FE/fe-sidedish/src/components/productDetailModal/ProductImages.jsx
  FE/fe-sidedish/src/components/productDetailModal/ProductInfo.jsx
  FE/fe-sidedish/src/components/productDetailModal/ProductOrder.jsx
  FE/fe-sidedish/src/components/productDetailModal/RelatedProduct.jsx
  FE/fe-sidedish/src/components/slider/Slide.jsx
  FE/fe-sidedish/src/components/slider/Slide.style.js
  FE/fe-sidedish/src/components/slider/SlideButton.jsx
  FE/fe-sidedish/src/components/slider/SlideCardList.jsx
  FE/fe-sidedish/src/components/slider/SlidePagination.jsx
  FE/fe-sidedish/src/constants/card.js
  FE/fe-sidedish/src/constants/portal.js
  FE/fe-sidedish/src/constants/productDetailModal.js
  FE/fe-sidedish/src/constants/slide.js
  FE/fe-sidedish/src/data/exhibition.js
  FE/fe-sidedish/src/data/productDetail.js
Labels: review-FE

#128 [TEAM-14][BE] 첫화면 조회, 상세보기 구현
  BE/BE-sidedish/README.md
  BE/BE-sidedish/build.gradle
  BE/BE-sidedish/src/main/java/team14/sidedish/config/JdbcConfiguration.java
  BE/BE-sidedish/src/main/java/team14/sidedish/config/SwaggerConfig.java
  BE/BE-sidedish/src/main/java/team14/sidedish/controller/SideDishController.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/Category.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/EventBadge.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/Menu.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/OrderInfo.java
  BE/BE-sidedish/src/main/java/team14/sidedish/domain/SaleInfo.java
  BE/BE-sidedish/src/main/java/team14/sidedish/event/Event.java
  BE/BE-sidedish/src/main/java/team14/sidedish/event/EventAndSalesDto.java
  BE/BE-sidedish/src/main/java/team14/sidedish/event/EventRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/event/EventService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/eventplanner/EventPlanner.java
  BE/BE-sidedish/src/main/java/team14/sidedish/eventplanner/EventPlannerDto.java
  BE/BE-sidedish/src/main/java/team14/sidedish/eventplanner/EventPlannerRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/eventplanner/EventPlannerService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/exhibition/Exhibition.java
  BE/BE-sidedish/src/main/java/team14/sidedish/exhibition/ExhibitionDto.java
  BE/BE-sidedish/src/main/java/team14/sidedish/exhibition/ExhibitionRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/exhibition/ExhibitionService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/image/Image.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/Menu.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuApiController.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuDto.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuModel.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/order/OrderInfo.java
  BE/BE-sidedish/src/main/java/team14/sidedish/order/RegionModel.java
  BE/BE-sidedish/src/main/java/team14/sidedish/repository/EventBadgeRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/repository/SideDishRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/salepolicy/DiscountPolicy.java
  BE/BE-sidedish/src/main/java/team14/sidedish/salepolicy/SalePolicy.java
  BE/BE-sidedish/src/main/java/team14/sidedish/service/EventBadgeService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/service/SideDishService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/specialmenu/SpecialMenu.java
  BE/BE-sidedish/src/main/java/team14/sidedish/specialmenu/SpecialMenuInfo.java
  BE/BE-sidedish/src/main/java/team14/sidedish/specialmenu/SpecialMenuRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/specialmenu/SpecialMenuService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/specialmenu/enums/SpecialMenuModel.java
  BE/BE-sidedish/src/main/java/team14/sidedish/specialmenu/enums/SpecialMenuValue.java
  BE/BE-sidedish/src/main/resources/application.properties
  BE/BE-sidedish/src/main/resources/data.sql
  BE/BE-sidedish/src/main/resources/db/mysql/data.sql
  BE/BE-sidedish/src/main/resources/db/mysql/schema.sql
  BE/BE-sidedish/src/main/resources/schemas.sql
  README.md
Labels: review-BE

#93 [Team-25 데이먼 & 벅픽] Side-dish 1주차 금요일 PR (엔티티, 레포지토리, 서비스 레이어 기본 구현)
  BE/src/main/java/com/team25/sidedish/domain/Category.java
  BE/src/main/java/com/team25/sidedish/domain/Delivery.java
  BE/src/main/java/com/team25/sidedish/domain/Event.java
  BE/src/main/java/com/team25/sidedish/domain/Image.java
  BE/src/main/java/com/team25/sidedish/domain/Product.java
  BE/src/main/java/com/team25/sidedish/domain/ProductEvent.java
  BE/src/main/java/com/team25/sidedish/exception/NotEnoughStockException.java
  BE/src/main/java/com/team25/sidedish/repository/CategoryRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ImageRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductDeliveryRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductEventRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductRepository.java
  BE/src/main/java/com/team25/sidedish/service/CategoryService.java
  BE/src/main/java/com/team25/sidedish/service/ImageService.java
  BE/src/main/java/com/team25/sidedish/service/ProductDeliveryService.java
  BE/src/main/java/com/team25/sidedish/service/ProductEventService.java
  BE/src/main/java/com/team25/sidedish/service/ProductService.java
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
  BE/src/test/java/com/team25/sidedish/repository/CategoryRepositoryTest.java
  BE/src/test/java/com/team25/sidedish/repository/ImageRepositoryTest.java
  BE/src/test/java/com/team25/sidedish/repository/ProductDeliveryRepositoryTest.java
  BE/src/test/java/com/team25/sidedish/repository/ProductEventRepositoryTest.java
  BE/src/test/java/com/team25/sidedish/repository/ProductRepositoryTest.java
Labels: review-BE

#135 [Team-03][BE][루이&쿠킴] - 로그인 제외한 모든 API 기능 구현, 배포
  BE/src/main/java/sidedish/com/config/WebConfig.java
  BE/src/main/java/sidedish/com/controller/DomainDtoMapper.java
  BE/src/main/java/sidedish/com/controller/OrderController.java
  BE/src/main/java/sidedish/com/controller/ProductsController.java
  BE/src/main/java/sidedish/com/controller/ProductsDtoMapper.java
  BE/src/main/java/sidedish/com/controller/model/OrderSaveRequest.java
  BE/src/main/java/sidedish/com/controller/model/OrderSaveResponse.java
  BE/src/main/java/sidedish/com/controller/model/ProductBasicTypeResponse.java
  BE/src/main/java/sidedish/com/controller/model/ProductDetailTypeResponse.java
  BE/src/main/java/sidedish/com/domain/DeliveryPolicy.java
  BE/src/main/java/sidedish/com/domain/DiscountPolicy.java
  BE/src/main/java/sidedish/com/domain/Order.java
  BE/src/main/java/sidedish/com/domain/Product.java
  BE/src/main/java/sidedish/com/exception/GlobalExceptionHandler.java
  BE/src/main/java/sidedish/com/exception/NoSuchProductsException.java
  BE/src/main/java/sidedish/com/exception/NotEnoughStockQuantityException.java
  BE/src/main/java/sidedish/com/repository/DeliveryPolicyRepository.java
  BE/src/main/java/sidedish/com/repository/DomainEntityMapper.java
  BE/src/main/java/sidedish/com/repository/OrderRepository.java
  BE/src/main/java/sidedish/com/repository/ProductsRepository.java
  BE/src/main/java/sidedish/com/repository/entity/DeliveryPolicyEntity.java
  BE/src/main/java/sidedish/com/repository/entity/DiscountPolicyEntity.java
  BE/src/main/java/sidedish/com/repository/entity/OrderEntity.java
  BE/src/main/java/sidedish/com/repository/entity/ProductEntity.java
  BE/src/main/java/sidedish/com/service/OrderService.java
  BE/src/main/java/sidedish/com/service/ProductsService.java
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/sidedish/com/acceptancetest/OrderAcceptanceTest.java
  BE/src/test/java/sidedish/com/acceptancetest/ProductsAcceptanceTest.java
  BE/src/test/java/sidedish/com/controller/OrderControllerTest.java
  BE/src/test/java/sidedish/com/controller/ProductsControllerTest.java
  BE/src/test/java/sidedish/com/domain/ProductTest.java
  BE/src/test/java/sidedish/com/repository/DeliveryPolicyRepositoryTest.java
  BE/src/test/java/sidedish/com/repository/ProductsRepositoryTest.java
  BE/src/test/resources/testdb/data.sql
  BE/src/test/resources/testdb/schema.sql
Labels: review-BE

#123 [Team-25] 리스트화면에서 상세화면 이동하기, 여러개의 이미지가져와 보여주기
  SideDishProject/Podfile
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject.xcworkspace/contents.xcworkspacedata
  SideDishProject/SideDishProject.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SideDishProject/SideDishProject/DishCollectionViewCell.swift
  SideDishProject/SideDishProject/HomeViewController.swift
  SideDishProject/SideDishProject/Info.plist
  SideDishProject/SideDishProject/ProductModel.swift
  SideDishProject/SideDishProject/ProductRepository.swift
  SideDishProject/SideDishProject/ProductSceneContainer.swift
  SideDishProject/SideDishProject/RootNavigationController.swift
  SideDishProject/SideDishProject/applifecycle/AppDelegate.swift
  SideDishProject/SideDishProject/applifecycle/SceneDelegate.swift
  SideDishProject/SideDishProject/model/Product.swift
  SideDishProject/SideDishProject/repository/MockDetailRepository.swift
  SideDishProject/SideDishProject/repository/ProductRepository.swift
  SideDishProject/SideDishProject/usecase/DetailUsecase.swift
  SideDishProject/SideDishProject/usecase/HomeUsecase.swift
  SideDishProject/SideDishProject/usecase/MockProductFactory.swift
  SideDishProject/SideDishProject/usecase/ProductSceneContainer.swift
  SideDishProject/SideDishProject/view/DetailViewController.swift
  SideDishProject/SideDishProject/view/DishCollectionDataSource.swift
  SideDishProject/SideDishProject/view/DishCollectionDelegate.swift
  SideDishProject/SideDishProject/view/DishCollectionViewCell.swift
  SideDishProject/SideDishProject/view/DishCommetHeaderView.swift
  SideDishProject/SideDishProject/view/HomeView.swift
  SideDishProject/SideDishProject/view/HomeViewController.swift
Labels: review-iOS

#120 [Android] Team 28 - MVVM 패턴 완성 & 모든 서버 API 통신 구현 완료
  android/.idea/deploymentTargetDropDown.xml
  android/.idea/misc.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/product_detail.json
  android/app/src/main/java/com/example/sidedish/ApiService.kt
  android/app/src/main/java/com/example/sidedish/AppModule.kt
  android/app/src/main/java/com/example/sidedish/AssetLoader.kt
  android/app/src/main/java/com/example/sidedish/BindingAdapter.kt
  android/app/src/main/java/com/example/sidedish/MainViewModel.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailActivity.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailDataSource.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailImageDataSource.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailRepository.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailTitleImage.kt
  android/app/src/main/java/com/example/sidedish/ProductDetailViewModel.kt
  android/app/src/main/java/com/example/sidedish/Products.kt
  android/app/src/main/java/com/example/sidedish/Repository.kt
  android/app/src/main/java/com/example/sidedish/ViewModelFactory.kt
  android/app/src/main/java/com/example/sidedish/model/Error.kt
  android/app/src/main/java/com/example/sidedish/model/MenuData.kt
  android/app/src/main/java/com/example/sidedish/model/PostRequest.kt
  android/app/src/main/java/com/example/sidedish/model/ProductDetail.kt
  android/app/src/main/java/com/example/sidedish/network/ApiService.kt
  android/app/src/main/java/com/example/sidedish/network/NetworkUtil.kt
  android/app/src/main/java/com/example/sidedish/network/RetrofitAPI.kt
  android/app/src/main/java/com/example/sidedish/repository/MainDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/MainRemoteDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/MainRepository.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductCountRemoteDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductDetailDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductDetailRemoteDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductDetailRepository.kt
  android/app/src/main/java/com/example/sidedish/ui/MainActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/MainHomeAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/MainViewModel.kt
  android/app/src/main/java/com/example/sidedish/ui/ProductDetailActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/ProductDetailImageAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/ProductDetailViewModel.kt
  android/app/src/main/java/com/example/sidedish/ui/common/BindingAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/common/ButtonState.kt
  android/app/src/main/java/com/example/sidedish/ui/common/GlideModule.kt
  android/app/src/main/java/com/example/sidedish/ui/common/HiltApplication.kt
  android/app/src/main/java/com/example/sidedish/ui/common/ViewModelFactory.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/activity_product_detail.xml
  android/app/src/main/res/layout/item_menu_data.xml
  android/app/src/main/res/layout/item_product_detail_image.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: review-android

#133 [Team-24][iOS] 구조개선 및 뷰모델 연결
  iOS/SideDish-team24/.swiftlint.yml
  iOS/SideDish-team24/SideDish-team24.xcodeproj/project.pbxproj
  iOS/SideDish-team24/SideDish-team24/Base.lproj/Main.storyboard
  iOS/SideDish-team24/SideDish-team24/Delegate/AppDelegate.swift
  iOS/SideDish-team24/SideDish-team24/Delegate/SceneDelegate.swift
  iOS/SideDish-team24/SideDish-team24/Extension/BriefBanchanViewControllerExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/CGFloatExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/IntExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/NotificationExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/StackViewExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/StringExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/UIButtonExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/UIColorExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/UIFontExtension.swift
  iOS/SideDish-team24/SideDish-team24/Extension/UILabelExtension.swift
  iOS/SideDish-team24/SideDish-team24/Font/SF-Pro-Display-Regular.otf
  iOS/SideDish-team24/SideDish-team24/Info.plist
  iOS/SideDish-team24/SideDish-team24/Model/Dish.swift
  iOS/SideDish-team24/SideDish-team24/Model/Dishes.swift
  iOS/SideDish-team24/SideDish-team24/Model/MockData.swift
  iOS/SideDish-team24/SideDish-team24/Model/Protocol/SideDishable.swift
  iOS/SideDish-team24/SideDish-team24/Util/NotificationKeyValue.swift
  iOS/SideDish-team24/SideDish-team24/Util/OrderCount.swift
  iOS/SideDish-team24/SideDish-team24/View/BriefBanchanViewCell.swift
  iOS/SideDish-team24/SideDish-team24/View/BriefView/BriefBanchanReusableView.swift
  iOS/SideDish-team24/SideDish-team24/View/CommonView/BanchanBriefView.swift
  iOS/SideDish-team24/SideDish-team24/View/CommonView/CustomLabel.swift
  iOS/SideDish-team24/SideDish-team24/View/CommonView/PaddingLabel.swift
  iOS/SideDish-team24/SideDish-team24/View/DetailBanchanBriefView.swift
  iOS/SideDish-team24/SideDish-team24/View/DetailBanchanView.swift
  iOS/SideDish-team24/SideDish-team24/View/DetailView/DeliverySectionView.swift
  iOS/SideDish-team24/SideDish-team24/View/DetailView/DetailViewBorder.swift
  iOS/SideDish-team24/SideDish-team24/View/DetailView/OrderCountSectionView.swift
  iOS/SideDish-team24/SideDish-team24/View/DetailView/OrderSectionView.swift
  iOS/SideDish-team24/SideDish-team24/View/OrderCountSectionView.swift
  iOS/SideDish-team24/SideDish-team24/ViewController/BriefBanchanViewController.swift
  iOS/SideDish-team24/SideDish-team24/ViewController/DetailBanchanViewController.swift
  iOS/SideDish-team24/SideDish-team24/ViewModel/BanchanViewModel.swift
Labels: review-iOS

#124 [Team-27] [Android] 백엔드 API연동 및 바인딩 어뎁터 적용
  .DS_Store
  android/.idea/.gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/sidedish/data/Category.kt
  android/app/src/main/java/com/example/sidedish/data/DataSource.kt
  android/app/src/main/java/com/example/sidedish/data/Food.kt
  android/app/src/main/java/com/example/sidedish/data/FoodDetail.kt
  android/app/src/main/java/com/example/sidedish/data/FoodImage.kt
  android/app/src/main/java/com/example/sidedish/data/Header.kt
  android/app/src/main/java/com/example/sidedish/data/Menu.kt
  android/app/src/main/java/com/example/sidedish/data/MenuListDataSource.kt
  android/app/src/main/java/com/example/sidedish/data/MenuListRepository.kt
  android/app/src/main/java/com/example/sidedish/data/MenuModel.kt
  android/app/src/main/java/com/example/sidedish/data/datasource/DataSource.kt
  android/app/src/main/java/com/example/sidedish/data/datasource/MenuListDataSource.kt
  android/app/src/main/java/com/example/sidedish/data/dto/JwtDTO.kt
  android/app/src/main/java/com/example/sidedish/data/dto/MenuDetailDTO.kt
  android/app/src/main/java/com/example/sidedish/data/dto/MenuListDTO.kt
  android/app/src/main/java/com/example/sidedish/data/repository/MenuListRepository.kt
  android/app/src/main/java/com/example/sidedish/di/Module.kt
  android/app/src/main/java/com/example/sidedish/network/ApiClient.kt
  android/app/src/main/java/com/example/sidedish/ui/MainActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/MenuItemClickListener.kt
  android/app/src/main/java/com/example/sidedish/ui/adapter/ImageViewPagerAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/adapter/MenuListAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/adapter/MenuPageAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/detail/MenuDetailFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/detail/MenuDetailTextAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/detail/MenuImageAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/login/LoginFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/HomeActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/HomeFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/MainMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/MenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/SideMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/SoupMenuFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/viewmodel/MenuListViewModel.kt
  android/app/src/main/res/drawable/ic_baseline_login_24.xml
  android/app/src/main/res/layout/activity_redirect.xml
  android/app/src/main/res/layout/fragment_detail.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_login.xml
  android/app/src/main/res/layout/item_menu_list.xml
  android/app/src/main/res/navigation/nav_graph.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/style.xml
  android/build.gradle
Labels: review-android

#167 [team-32][BE][선을로&헤이호] 4번째 PR 요청
  be/build.gradle
  be/src/main/java/kr/codesquad/sidedish/SidedishApplication.java
  be/src/main/java/kr/codesquad/sidedish/config/WebConfig.java
  be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
  be/src/main/java/kr/codesquad/sidedish/controller/ResponseDetailProductInfo.java
  be/src/main/java/kr/codesquad/sidedish/controller/ResponseShippingInfo.java
  be/src/main/java/kr/codesquad/sidedish/controller/ResponseSimpleProductInfo.java
  be/src/main/java/kr/codesquad/sidedish/domain/DeliveryType.java
  be/src/main/java/kr/codesquad/sidedish/domain/DiscountType.java
  be/src/main/java/kr/codesquad/sidedish/domain/DishType.java
  be/src/main/java/kr/codesquad/sidedish/domain/Product.java
  be/src/main/java/kr/codesquad/sidedish/domain/ShippingInfo.java
  be/src/main/java/kr/codesquad/sidedish/domain/SideDishType.java
  be/src/main/java/kr/codesquad/sidedish/exception/CustomException.java
  be/src/main/java/kr/codesquad/sidedish/repository/MemoryProductRepository.java
  be/src/main/java/kr/codesquad/sidedish/repository/ProductRepository.java
  be/src/main/java/kr/codesquad/sidedish/repository/ShippingInfoRepository.java
  be/src/main/java/kr/codesquad/sidedish/response/CommonCode.java
  be/src/main/java/kr/codesquad/sidedish/response/ErrorCode.java
  be/src/main/java/kr/codesquad/sidedish/service/ProductDTO.java
  be/src/main/java/kr/codesquad/sidedish/service/ProductService.java
  be/src/main/java/kr/codesquad/sidedish/service/ServiceValidator.java
  be/src/main/java/kr/codesquad/sidedish/service/ShippingInfoDTO.java
  be/src/main/java/kr/codesquad/sidedish/service/ShippingInfoService.java
  be/src/main/resources/sql/data.sql
  be/src/main/resources/sql/schema.sql
  be/src/test/java/kr/codesquad/sidedish/domain/DishTypeTest.java
  be/src/test/java/kr/codesquad/sidedish/domain/SideDishTypeTestType.java
  be/src/test/java/kr/codesquad/sidedish/repository/ProductRepositoryTest.java
  be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
Labels: review-BE

#163 [Team -18] Eddy & Kai : Home View , 데이터 바인딩 구현
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp/Common/Obseverable.swift
  SideDishApp/SideDishApp/Common/Typography.swift
  SideDishApp/SideDishApp/Model/Category.swift
  SideDishApp/SideDishApp/Model/Entity/Badge.swift
  SideDishApp/SideDishApp/Model/Entity/Category.swift
  SideDishApp/SideDishApp/Model/Entity/CurrencyFormattable.swift
  SideDishApp/SideDishApp/Model/Entity/Delivery.swift
  SideDishApp/SideDishApp/Model/Entity/Money.swift
  SideDishApp/SideDishApp/Model/Entity/ProductDetail.swift
  SideDishApp/SideDishApp/Model/Entity/ProductSummary.swift
  SideDishApp/SideDishApp/Model/Networking/APIRequestable.swift
  SideDishApp/SideDishApp/Model/Networking/CategoryRequest.swift
  SideDishApp/SideDishApp/Model/Networking/ImageRequest.swift
  SideDishApp/SideDishApp/Model/Networking/NetworkError.swift
  SideDishApp/SideDishApp/Model/Networking/NetworkManager.swift
  SideDishApp/SideDishApp/Model/Networking/ProductDetailRequest.swift
  SideDishApp/SideDishApp/Model/ProductDetail.swift
  SideDishApp/SideDishApp/Model/ProductType.swift
  SideDishApp/SideDishApp/Networking/NetworkManager.swift
  SideDishApp/SideDishApp/Resource/Assets.xcassets/ImagePlaceHolder.imageset/Contents.json
  SideDishApp/SideDishApp/Resource/Assets.xcassets/ImagePlaceHolder.imageset/ImagePlaceHolder.png
  SideDishApp/SideDishApp/Service/CategoryManager.swift
  SideDishApp/SideDishApp/View/BadgeLabel.swift
  SideDishApp/SideDishApp/View/Base.lproj/Main.storyboard
  SideDishApp/SideDishApp/View/CollectionViewLayoutFactory.swift
  SideDishApp/SideDishApp/View/HeaderView.swift
  SideDishApp/SideDishApp/View/MainBackgroundView.swift
  SideDishApp/SideDishApp/View/MainCollectionViewCell.swift
  SideDishApp/SideDishApp/View/MainCollectionViewCell.xib
  SideDishApp/SideDishApp/View/MainCollectionViewSectionHeader.swift
  SideDishApp/SideDishApp/View/MainViewController.swift
  SideDishApp/SideDishApp/ViewModel/MainCollectionViewModel.swift
  SideDishApp/SideDishApp/ViewModel/OrderViewModel.swift
  SideDishApp/SideDishApp/ViewModel/ProductCellViewModel.swift
  SideDishApp/SideDishApp/ViewModel/ProductCollectionViewModel.swift
  SideDishApp/SideDishApp/ViewModel/ProductDetailViewModel.swift
  SideDishApp/SideDishAppTests/CategoryManagerTests.swift
  SideDishApp/SideDishAppTests/NetworkManagerTests.swift
  SideDishApp/SideDishAppTests/ProductCollectionViewModelTests.swift
  SideDishApp/SideDishAppTests/ProductDecodingTests.swift
  SideDishApp/SideDishAppTests/ProductDetailDecodingTest.swift
Labels: review-iOS

#144 [team-15] iOS - bibi & puco 세 번째 PR 입니다!
  sidedishApp/sidedishApp.xcodeproj/project.pbxproj
  sidedishApp/sidedishApp.xcodeproj/xcshareddata/xcschemes/sidedishApp.xcscheme
  sidedishApp/sidedishApp.xcodeproj/xcuserdata/bibi.xcuserdatad/xcschemes/xcschememanagement.plist
  sidedishApp/sidedishApp/Base.lproj/Main.storyboard
  sidedishApp/sidedishApp/CardFactory.swift
  sidedishApp/sidedishApp/Info.plist
  sidedishApp/sidedishApp/model/Badge.swift
  sidedishApp/sidedishApp/model/DetailCard.swift
  sidedishApp/sidedishApp/model/Dish.swift
  sidedishApp/sidedishApp/model/MainCard.swift
  sidedishApp/sidedishApp/model/SideDishManager.swift
  sidedishApp/sidedishApp/network/HTTPManager.swift
  sidedishApp/sidedishApp/network/HTTPMethod.swift
  sidedishApp/sidedishApp/network/ImageManager.swift
  sidedishApp/sidedishApp/network/JSONConverter.swift
  sidedishApp/sidedishApp/util/UIColorExtension.swift
  sidedishApp/sidedishApp/util/UIFontExtension.swift
  sidedishApp/sidedishApp/util/UIStackViewExtension.swift
  sidedishApp/sidedishApp/viewController/detail/DetailViewController.swift
  sidedishApp/sidedishApp/viewController/detail/MainDescriptionViewController.swift
  sidedishApp/sidedishApp/viewController/detail/OrderViewController.swift
  sidedishApp/sidedishApp/viewController/detail/SubDescriptionViewController.swift
  sidedishApp/sidedishApp/viewController/main/BadgeLabel.swift
  sidedishApp/sidedishApp/viewController/main/BadgeStackView.swift
  sidedishApp/sidedishApp/viewController/main/MainViewCardCell.swift
  sidedishApp/sidedishApp/viewController/main/MainViewCardInfo.swift
  sidedishApp/sidedishApp/viewController/main/MainViewController.swift
  sidedishApp/sidedishApp/viewController/main/MainViewHeader.swift
Labels: review-iOS

#150 [Team-16][iOS] DetailView 구현
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp/Controller/Delegate & DataSource/OrderingCollectionViewDataSource.swift
  SideDishApp/SideDishApp/Controller/Delegate & DataSource/OrderingCollectionViewDelegate.swift
  SideDishApp/SideDishApp/Controller/Delegate & DataSource/SectionHeaderDelegate.swift
  SideDishApp/SideDishApp/Controller/DetailViewController.swift
  SideDishApp/SideDishApp/Controller/OrderingViewController.swift
  SideDishApp/SideDishApp/Extension/UIColor+Extension.swift
  SideDishApp/SideDishApp/Model/PriceConvertor.swift
  SideDishApp/SideDishApp/Network/EndPoint.swift
  SideDishApp/SideDishApp/Network/NetworkManager.swift
  SideDishApp/SideDishApp/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  SideDishApp/SideDishApp/SupportingFiles/Constant.swift
  SideDishApp/SideDishApp/View/DetailScrollView.swift
  SideDishApp/SideDishApp/View/MenuStackView.swift
  SideDishApp/SideDishApp/View/MenuSubInfoContainerStackView.swift
  SideDishApp/SideDishApp/View/OrderingCollectionViewCell.swift
  SideDishApp/SideDishApp/View/SectionHeaderView.swift
Labels: review-iOS

#121 [team-10][FE][이든, Khan] 반찬가게 Step3
  public/data/mainDish.json
  public/index.html
  src/App.js
  src/Header.js
  src/MainCard.js
  src/SubCard.js
  src/components/Button.js
  src/components/Card.js
  src/components/CardBox.js
  src/components/CategoryTitle.js
  src/components/Gnb.js
  src/components/GnbItem.js
  src/components/Infos.js
  src/components/Menu.js
  src/components/Slider.js
  src/components/Tab.js
  src/container/CardContainer.js
  src/utility/util.js
Labels: review-FE

#161 [TEAM-24] [땃쥐, Lee] BE 세번째 PR입니다.
  BE/src/main/java/codesquad/sidedish/domain/delivery/Delivery.java
  BE/src/main/java/codesquad/sidedish/domain/delivery/DeliveryRepository.java
  BE/src/main/java/codesquad/sidedish/domain/discount/DiscountPolicy.java
  BE/src/main/java/codesquad/sidedish/domain/item/Item.java
  BE/src/main/java/codesquad/sidedish/domain/item/ItemImage.java
  BE/src/main/java/codesquad/sidedish/domain/item/ItemImageType.java
  BE/src/main/java/codesquad/sidedish/domain/item/ItemRepository.java
  BE/src/main/java/codesquad/sidedish/domain/item/ItemSection.java
  BE/src/main/java/codesquad/sidedish/domain/member/Member.java
  BE/src/main/java/codesquad/sidedish/domain/member/MemberRepository.java
  BE/src/main/java/codesquad/sidedish/domain/order/Order.java
  BE/src/main/java/codesquad/sidedish/domain/order/OrderRepository.java
  BE/src/main/java/codesquad/sidedish/exception/ErrorResult.java
  BE/src/main/java/codesquad/sidedish/exception/ItemNotFoundException.java
  BE/src/main/java/codesquad/sidedish/exception/MyExceptionHandler.java
  BE/src/main/java/codesquad/sidedish/exception/NotEnoughStockException.java
  BE/src/main/java/codesquad/sidedish/service/ItemService.java
  BE/src/main/java/codesquad/sidedish/web/controller/ItemController.java
  BE/src/main/java/codesquad/sidedish/web/dto/ItemDetailResponse.java
  BE/src/main/java/codesquad/sidedish/web/dto/ItemListElement.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/codesquad/sidedish/domain/delivery/DeliveryRepositoryTest.java
  BE/src/test/java/codesquad/sidedish/domain/discount/DiscountPolicyTest.java
  BE/src/test/java/codesquad/sidedish/domain/item/ItemRepositoryTest.java
  BE/src/test/java/codesquad/sidedish/domain/item/ItemTest.java
  BE/src/test/java/codesquad/sidedish/domain/member/MemberRepositoryTest.java
  BE/src/test/java/codesquad/sidedish/domain/member/MemberTest.java
  BE/src/test/java/codesquad/sidedish/domain/order/OrderRepositoryTest.java
Labels: review-BE

#155 [JinSol] UI & Model
  SideDish/.SwiftLint.yml
  SideDish/SideDish.xcodeproj/project.pbxproj
  SideDish/SideDish/Base/Base.lproj/Main.storyboard
  SideDish/SideDish/Base/Info.plist
  SideDish/SideDish/Extensions/String+.swift
  SideDish/SideDish/Model/DiscountType.swift
  SideDish/SideDish/Model/DishCellRepository.swift
  SideDish/SideDish/Model/DishDetailRepository.swift
  SideDish/SideDish/Model/Entity/DetailData.swift
  SideDish/SideDish/Model/Entity/DishCellInfo.swift
  SideDish/SideDish/Model/Entity/DishDetail.swift
  SideDish/SideDish/Model/Product.swift
  SideDish/SideDish/Support/CellFactory.swift
  SideDish/SideDish/Support/NetworkError.swift
  SideDish/SideDish/Support/ProductSort.swift
  SideDish/SideDish/View/AmountSectionView.swift
  SideDish/SideDish/View/DeliverySectionView.swift
  SideDish/SideDish/View/DetailDishSectionView.swift
  SideDish/SideDish/View/DetailView.swift
  SideDish/SideDish/View/DetailViewController.swift
  SideDish/SideDish/View/DishCell.swift
  SideDish/SideDish/View/DishCell.xib
  SideDish/SideDish/View/HomeViewController.swift
  SideDish/SideDish/View/SectionHeader.swift
  SideDish/SideDish/ViewModel/DishCellViewModel.swift
  SideDish/SideDish/ViewModel/DishDetailViewModel.swift
Labels: review-iOS

#168 [Team-20] 2주차 수요일 애플리케이션 구조 수정 및 상세화면 작업
  SideDish20/SideDish20.xcodeproj/project.pbxproj
  SideDish20/SideDish20/Application/Assets.xcassets/Color/Gret3.colorset/Contents.json
  SideDish20/SideDish20/Application/SceneDelegate.swift
  SideDish20/SideDish20/Model/CacheImageMiddleWare.swift
  SideDish20/SideDish20/Model/CacheImageModel.swift
  SideDish20/SideDish20/Model/CacheImageRequestMiddleWare.swift
  SideDish20/SideDish20/Model/CacheImageRequestModel.swift
  SideDish20/SideDish20/Model/CacheModelFactory.swift
  SideDish20/SideDish20/Model/HomeDataFetchModel.swift
  SideDish20/SideDish20/Model/HomeResponseData.swift
  SideDish20/SideDish20/Model/SideDishModel.swift
  SideDish20/SideDish20/Repository/Network/CommonURLManager.swift
  SideDish20/SideDish20/Repository/Network/DataFetchService.swift
  SideDish20/SideDish20/Repository/RepositoryCommons.swift
  SideDish20/SideDish20/View/Home.storyboard
  SideDish20/SideDish20/View/HomeDetailCollectionViewCell.swift
  SideDish20/SideDish20/View/HomeDetailCollectionViewCell.xib
  SideDish20/SideDish20/ViewController/DetailViewController.swift
  SideDish20/SideDish20/ViewController/HomeNavigationController.swift
  SideDish20/SideDish20/ViewController/HomeViewController.swift
  SideDish20/SideDish20/ViewModel/CommonViewModel.swift
  SideDish20/SideDish20/ViewModel/DishViewModel.swift
  SideDish20/SideDish20/ViewModel/HomeViewModel.swift
Labels: review-iOS

#149 [Team-17][iOS] 모델링 및 이미지 관리 작업
  BanchanApp/.swiftlint.yml
  BanchanApp/BanchanApp.xcodeproj/project.pbxproj
  BanchanApp/BanchanApp/API/Base/NetworkError.swift
  BanchanApp/BanchanApp/API/Base/NetworkResult.swift
  BanchanApp/BanchanApp/API/Base/URLSession+Extension.swift
  BanchanApp/BanchanApp/API/Base/URLSessionDataTaskMock.swift
  BanchanApp/BanchanApp/API/Base/URLSessionMock.swift
  BanchanApp/BanchanApp/API/NetworkManager.swift
  BanchanApp/BanchanApp/Controllers/BanchanDetailViewController.storyboard
  BanchanApp/BanchanApp/Controllers/BanchanDetailViewController.swift
  BanchanApp/BanchanApp/Controllers/BanchanListViewController.storyboard
  BanchanApp/BanchanApp/Controllers/BanchanListViewController.swift
  BanchanApp/BanchanApp/Models/BanchanListViewModel.swift
  BanchanApp/BanchanApp/Models/Domains/Banchan.swift
  BanchanApp/BanchanApp/Models/Domains/Price.swift
  BanchanApp/BanchanApp/Models/Entities/Product.swift
  BanchanApp/BanchanApp/Models/Entities/ProductDetail.swift
  BanchanApp/BanchanApp/Models/Entities/ProductResponse.swift
  BanchanApp/BanchanApp/Repository/RemoteRepository.swift
  BanchanApp/BanchanApp/SceneDelegate.swift
  BanchanApp/BanchanApp/Services/Base/ImageManager.swift
  BanchanApp/BanchanApp/Services/Service.swift
  BanchanApp/BanchanApp/Utility/Configuration.swift
  BanchanApp/BanchanApp/Utility/Observable.swift
  BanchanApp/BanchanApp/Utility/UIFont+Extension.swift
  BanchanApp/BanchanApp/Utility/UIStackView+Extension.swift
  BanchanApp/BanchanApp/Views/BadgeLabel.swift
  BanchanApp/BanchanApp/Views/CarouselView.swift
  BanchanApp/BanchanApp/Views/PriceTag.swift
  BanchanApp/BanchanApp/Views/ProductDetailCell.swift
  BanchanApp/BanchanApp/Views/ProductDetailView.swift
  BanchanApp/BanchanApp/Views/ProductSectionHeader.swift
  BanchanApp/BanchanApp/Views/QuantityView.swift
  BanchanApp/Debug.xcconfig
  BanchanApp/Release.xcconfig
  README.md
Labels: review-iOS

#117 [Team 30] [Android] 주문하기 네트워크 처리, 섬네일 이미지 Index처리, 메뉴 리스트 헤더 클릭 처리, 코루틴 예외처리 적용
  app/src/main/java/com/example/todo/sidedish/config/Config.kt
  app/src/main/java/com/example/todo/sidedish/data/dto/OrderDto.kt
  app/src/main/java/com/example/todo/sidedish/data/remote/order/OrderApi.kt
  app/src/main/java/com/example/todo/sidedish/data/remote/order/OrderDataSource.kt
  app/src/main/java/com/example/todo/sidedish/data/remote/order/OrderRemoteDataSource.kt
  app/src/main/java/com/example/todo/sidedish/data/repository/MenuRepositoryImpl.kt
  app/src/main/java/com/example/todo/sidedish/data/repository/ProductOrderRepositoryImpl.kt
  app/src/main/java/com/example/todo/sidedish/di/Annotation.kt
  app/src/main/java/com/example/todo/sidedish/di/DataSourceModule.kt
  app/src/main/java/com/example/todo/sidedish/di/NetworkModule.kt
  app/src/main/java/com/example/todo/sidedish/di/RepositoryModule.kt
  app/src/main/java/com/example/todo/sidedish/domain/OrderRepository.kt
  app/src/main/java/com/example/todo/sidedish/domain/Repository.kt
  app/src/main/java/com/example/todo/sidedish/domain/model/Header.kt
  app/src/main/java/com/example/todo/sidedish/domain/model/Order.kt
  app/src/main/java/com/example/todo/sidedish/ui/common/TextBindingAdapters.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuAdapter.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuViewModel.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/MenuDetailFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/MenuDetailViewModel.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/OrderCancelDialogFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/ViewPagerAdapter.kt
  app/src/main/res/layout/fragment_menu_detail.xml
  app/src/main/res/layout/fragment_order_cancel_dialog.xml
  app/src/main/res/layout/item_header.xml
  app/src/main/res/layout/item_viewpager.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: review-android

#119 [Team-29][Android] 2차 피드백 적용 + 네트워크 및 힐트 적용
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sideDish/MainActivity.kt
  app/src/main/java/com/example/sideDish/SideDishApplication.kt
  app/src/main/java/com/example/sideDish/common/ViewModelFactory.kt
  app/src/main/java/com/example/sideDish/data/model/FoodCategory.kt
  app/src/main/java/com/example/sideDish/data/model/FoodDetail.kt
  app/src/main/java/com/example/sideDish/data/model/Item.kt
  app/src/main/java/com/example/sideDish/data/source/DetailRemoteRepository.kt
  app/src/main/java/com/example/sideDish/data/source/DetailRepository.kt
  app/src/main/java/com/example/sideDish/data/source/FoodRemoteRepository.kt
  app/src/main/java/com/example/sideDish/data/source/FoodRepository.kt
  app/src/main/java/com/example/sideDish/di/NetworkModule.kt
  app/src/main/java/com/example/sideDish/di/RepositoryModule.kt
  app/src/main/java/com/example/sideDish/network/SideDishRetrofitService.kt
  app/src/main/java/com/example/sideDish/network/dto/DetailDto.kt
  app/src/main/java/com/example/sideDish/network/dto/SideDishDto.kt
  app/src/main/java/com/example/sideDish/ui/BindingAdapters.kt
  app/src/main/java/com/example/sideDish/ui/Stepper.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListAdapter.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListFragment.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListViewModel.kt
  app/src/main/java/com/example/sideDish/ui/productdetail/FoodDetailViewModel.kt
  app/src/main/java/com/example/sideDish/ui/productdetail/ProductDetailFragment.kt
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/main_summary_item.xml
  app/src/main/res/layout/section.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-android

#139 [Team-19 iOS Chez & Jason] SideDish - 메인화면 구현
  sideDish/.DS_Store
  sideDish/.swiftlint.yml
  sideDish/sideDish.xcodeproj/project.pbxproj
  sideDish/sideDish/.DS_Store
  sideDish/sideDish/AppDelegate.swift
  sideDish/sideDish/CollectionHeaderView.swift
  sideDish/sideDish/Extension/UIColor+Extension.swift
  sideDish/sideDish/Info.plist
  sideDish/sideDish/JSON/JsonConvertor.swift
  sideDish/sideDish/JSON/main.json
  sideDish/sideDish/JSON/mock.json
  sideDish/sideDish/JSON/side.json
  sideDish/sideDish/JSON/soup.json
  sideDish/sideDish/Model/Food.swift
  sideDish/sideDish/Model/FoodManager.swift
  sideDish/sideDish/Model/NetworkManager.swift
  sideDish/sideDish/SceneDelegate.swift
  sideDish/sideDish/View/FoodCell.swift
  sideDish/sideDish/ViewController/MainViewController.swift
  sideDish/sideDishTests/DecodingEncodingTest.swift
  sideDish/sideDishTests/sideDishTests.swift
Labels: review-iOS

#210 [Team 09] [dony, 럼카] 2주차 2번째 PR 요청드립니다.
  .gitignore
  src/Sidedish.jsx
  src/components/Header/GNB.jsx
  src/components/Header/MyUtils.jsx
  src/components/Header/SubGNB.jsx
  src/components/MainCategory/Contents.jsx
  src/components/MainCategory/MainCategory.jsx
  src/components/MainCategory/Tab/TabBar.jsx
  src/components/MainCategory/Tab/TabButton.jsx
  src/components/MenuSection/MenuSection.jsx
  src/components/MenuSection/MenuSlider.jsx
  src/components/Modal/DeliveryInfo.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Picture.jsx
  src/components/MoreButton.jsx
  src/components/common/Card/Card.jsx
  src/components/common/Card/Tag.jsx
  src/components/common/IconButton.jsx
  src/variable/theme.js
Labels: review-FE

#184 [BE][Team-07][케이&반스] 2주차 금요일 PR
  BE/build.gradle
  BE/src/main/java/kr/codesquad/sidedish/controller/ItemController.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Item.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Order.java
  BE/src/main/java/kr/codesquad/sidedish/exception/HandlerAdvice.java
  BE/src/main/java/kr/codesquad/sidedish/repository/ItemRepository.java
  BE/src/main/java/kr/codesquad/sidedish/repository/OrderRepository.java
  BE/src/main/java/kr/codesquad/sidedish/service/OrderService.java
  BE/src/main/java/kr/codesquad/sidedish/web/dto/ErrorDto.java
  BE/src/main/java/kr/codesquad/sidedish/web/dto/item/ItemDetailResponseDto.java
  BE/src/main/java/kr/codesquad/sidedish/web/dto/item/ItemListResponseDto.java
  BE/src/main/java/kr/codesquad/sidedish/web/dto/item/ItemResponseDto.java
  BE/src/main/java/kr/codesquad/sidedish/web/dto/order/OrderRequest.java
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
Labels: review-BE

#183 [BE][Team-26] 2주차 2차 PR
  BE/README.md
  BE/src/main/java/sidedish/jbc/config/WebConfig.java
  BE/src/main/java/sidedish/jbc/controller/OAuthController.java
  BE/src/main/java/sidedish/jbc/domain/SaleType.java
  BE/src/main/java/sidedish/jbc/dto/DetailMenuResponse.java
  BE/src/main/java/sidedish/jbc/dto/MenuOrderResponse.java
  BE/src/main/java/sidedish/jbc/dto/MenuResponse.java
  BE/src/main/java/sidedish/jbc/interceptor/LoginCheckInterceptor.java
  BE/src/main/java/sidedish/jbc/repository/MenuRepository.java
  BE/src/main/java/sidedish/jbc/service/MenuService.java
  BE/src/main/java/sidedish/jbc/service/OrderService.java
Labels: review-BE

#195 [Team-27][BE] Lucid & 산토리 - 2주차 2차 PR
  backend/build.gradle
  backend/src/main/java/com/codesquad/sidedish/config/OpenApiConfig.java
  backend/src/main/java/com/codesquad/sidedish/item/controller/ItemController.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/Item.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/ItemImage.java
  backend/src/main/java/com/codesquad/sidedish/item/domain/ItemRepository.java
  backend/src/main/java/com/codesquad/sidedish/item/service/ItemService.java
  backend/src/main/java/com/codesquad/sidedish/order/controller/OrderController.java
  backend/src/main/java/com/codesquad/sidedish/order/dto/OrderItemDto.java
  backend/src/main/java/com/codesquad/sidedish/order/service/OrderService.java
  backend/src/main/java/com/codesquad/sidedish/user/controller/LoginController.java
  backend/src/main/java/com/codesquad/sidedish/user/controller/interceptor/AuthenticationInterceptor.java
  backend/src/main/java/com/codesquad/sidedish/user/domain/UserRepository.java
  backend/src/main/java/com/codesquad/sidedish/user/dto/UserProfileDto.java
  backend/src/main/java/com/codesquad/sidedish/user/service/JwtTokenProvider.java
  backend/src/main/java/com/codesquad/sidedish/user/service/LoginService.java
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/com/codesquad/sidedish/item/domain/ItemTest.java
Labels: review-BE

#207 [Team-13][BE] 반찬가게 프로젝트 마지막 PR입니다~
  backend/src/main/java/kr/codesquad/sidedish/advice/ExceptionHandlerAdvice.java
  backend/src/main/java/kr/codesquad/sidedish/configuration/CorsConfig.java
  backend/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
  backend/src/main/java/kr/codesquad/sidedish/controller/ThemeController.java
  backend/src/main/java/kr/codesquad/sidedish/controller/dto/ProductListRequest.java
  backend/src/main/java/kr/codesquad/sidedish/controller/dto/ThemeListResponse.java
  backend/src/main/java/kr/codesquad/sidedish/service/ProductService.java
Labels: review-BE

#194 [TEAM-14][BE][Tany & Sally] 반찬가계 기능구현 최종 PR
  BE/BE-sidedish/README.md
  BE/BE-sidedish/build.gradle
  BE/BE-sidedish/src/main/java/team14/sidedish/common/Exception/InvalidOrderException.java
  BE/BE-sidedish/src/main/java/team14/sidedish/common/error/Error.java
  BE/BE-sidedish/src/main/java/team14/sidedish/common/error/ErrorResponse.java
  BE/BE-sidedish/src/main/java/team14/sidedish/common/error/GlobalControllerAdvice.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/Menu.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuApiController.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuDto.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/menu/MenuService.java
  BE/BE-sidedish/src/main/java/team14/sidedish/order/Order.java
  BE/BE-sidedish/src/main/java/team14/sidedish/order/OrderDto.java
  BE/BE-sidedish/src/main/java/team14/sidedish/order/OrderInfo.java
  BE/BE-sidedish/src/main/java/team14/sidedish/order/OrderRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/specialmenu/SpecialMenuRepository.java
  BE/BE-sidedish/src/main/java/team14/sidedish/specialmenu/enums/SpecialMenuModel.java
  BE/BE-sidedish/src/main/resources/db/mysql/data.sql
  BE/BE-sidedish/src/main/resources/db/mysql/schema.sql
Labels: review-BE

#219 [Jinsol] 리팩토링 및 Cell 이미지 추가
  SideDish/SideDish.xcodeproj/project.pbxproj
  SideDish/SideDish/Model/DetailStringData.swift
  SideDish/SideDish/Model/DishCellRepository.swift
  SideDish/SideDish/Model/DishDetailRepository.swift
  SideDish/SideDish/Model/Entity/DetailData.swift
  SideDish/SideDish/Model/Product.swift
  SideDish/SideDish/Support/CellFactory.swift
  SideDish/SideDish/Support/NetworkTarget.swift
  SideDish/SideDish/Support/ProductSort.swift
  SideDish/SideDish/View/AmountSectionView.swift
  SideDish/SideDish/View/DeliverySectionView.swift
  SideDish/SideDish/View/DetailDishSectionView.swift
  SideDish/SideDish/View/DetailViewController.swift
  SideDish/SideDish/View/DishCell.swift
  SideDish/SideDish/View/HomeViewController.swift
  SideDish/SideDish/View/PaddingLabel.swift
  SideDish/SideDish/ViewModel/DishCellViewModel.swift
  SideDish/SideDish/ViewModel/DishDetailViewModel.swift
Labels: review-iOS

#176 [Team34][BE] 주문 기능 구현과 프론트 배포
  BE/src/main/java/com/team34/sidedish/config/WebMvcConfig.java
  BE/src/main/java/com/team34/sidedish/controller/OrderController.java
  BE/src/main/java/com/team34/sidedish/domain/Dish.java
  BE/src/main/java/com/team34/sidedish/domain/Order.java
  BE/src/main/java/com/team34/sidedish/dto/OrderRequest.java
  BE/src/main/java/com/team34/sidedish/exception/OutOfStockException.java
  BE/src/main/java/com/team34/sidedish/interceptor/CorsInterceptor.java
  BE/src/main/java/com/team34/sidedish/repository/OrderRepository.java
  BE/src/main/java/com/team34/sidedish/service/OrderService.java
  BE/src/main/resources/data.sql
Labels: review-BE

#187 [team-04][FE] 도비 & Muffin PR 2주차 금 PR
  fe/.env
  fe/.gitignore
  fe/src/Callback.jsx
  fe/src/Header/HeaderLogin.jsx
  fe/src/Main/Card.jsx
  fe/src/Main/CardModal.jsx
  fe/src/Main/Dish/DishCategoryAllButton.jsx
  fe/src/Main/Dish/DishContainer.jsx
  fe/src/Main/MainContainer.jsx
  fe/src/Main/Recommend/RecommendTab.jsx
  fe/src/Modal/ModalDetailContainer.jsx
  fe/src/Modal/ModalImgWrapper.jsx
  fe/src/Modal/ModalOrderInfo.jsx
  fe/src/Modal/ModalTogatherContainer.jsx
  fe/src/common/Error.jsx
  fe/src/common/Loading.jsx
  fe/src/constant.js
  fe/src/image/loading.gif
  fe/src/theme.jsx
  fe/src/useFetch.jsx
  fe/src/util.js
Labels: review-FE

#199 [team-12][FE] Jimmy & Park 2주차 두 번째 PR
  .vscode/settings.json
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/src/apis/categoriesApi.js
  FE/src/apis/client.js
  FE/src/common/utils.js
  FE/src/components/Button.js
  FE/src/components/Carousel/ModalCarouselProvider.js
  FE/src/components/Icons/MinusIcon.js
  FE/src/components/Icons/PlusIcon.js
  FE/src/components/Main/FoodCard.js
  FE/src/components/Main/FoodCards.js
  FE/src/components/Main/Main.js
  FE/src/components/Main/MainContent.js
  FE/src/components/Main/MainTabs.js
  FE/src/components/Main/SubContent.js
  FE/src/components/Main/SubContents.js
  FE/src/components/Modal/FoodModal.js
  FE/src/components/Modal/Modal.js
  FE/src/components/Modal/OrderButton.js
  FE/src/components/Modal/ProductDetail.js
  FE/src/components/Modal/ProductImg.js
  FE/src/components/Modal/ProductInfo.js
  FE/src/components/Modal/RelatedProduct.js
  FE/src/components/Modal/TotalAmount.js
  FE/src/components/Modal/TotalCost.js
  FE/src/constants/badge.js
  FE/src/constants/fonts.js
  FE/src/context/ModalCardInfoContext.js
  FE/src/mocks/foods.js
  FE/src/mocks/mainTabs.js
  FE/src/mocks/subContents.js
  FE/src/mocks/subFoods.js
  FE/src/mocks/tabs.js
Labels: review-FE

#193 [TEAM-20] 프로젝트 마무리. 필요한 기능구현 및 배포.
  SideDish20/SideDish20.xcodeproj/project.pbxproj
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/100.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/1024.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/114.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/120.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/128.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/144.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/152.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/16.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/167.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/172.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/180.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/196.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/20.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/216.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/256.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/29.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/32.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/40.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/48.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/50.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/512.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/55.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/57.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/58.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/60.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/64.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/72.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/76.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/80.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/87.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/88.png
  SideDish20/SideDish20/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
  SideDish20/SideDish20/Info.plist
  SideDish20/SideDish20/Model/HomeDataFetchModel.swift
  SideDish20/SideDish20/Model/HomeModel.swift
  SideDish20/SideDish20/Model/HomeResponseDetailData.swift
  SideDish20/SideDish20/Repository/Network/CommonURLManager.swift
  SideDish20/SideDish20/Repository/Network/DataFetchService.swift
  SideDish20/SideDish20/Repository/RepositoryCommons.swift
  SideDish20/SideDish20/View/Home.storyboard
  SideDish20/SideDish20/View/HomeCollectionViewCell.swift
  SideDish20/SideDish20/View/HomeCollectionViewCell.xib
  SideDish20/SideDish20/ViewController/DetailViewController.swift
  SideDish20/SideDish20/ViewController/HomeViewController.swift
  SideDish20/SideDish20/ViewModel/CacheViewModel.swift
  SideDish20/SideDish20/ViewModel/DetailViewModel.swift
  SideDish20/SideDish20/ViewModel/HomeViewModel.swift
  SideDish20/SideDish20/ViewModel/Observer.swift
  SideDish20/SideDish20Tests/SideDish20FileManagerTest.swift
Labels: review-iOS

#200 [team-11] 2주차 2번째 PR Nick + J
  src/App.js
  src/Components/List.jsx
  src/Components/SlideButton.jsx
  src/Components/header/GNB.jsx
  src/Components/main/BestProduct.jsx
  src/Components/main/Category.jsx
  src/Components/main/food/Card.jsx
  src/Components/main/food/List.jsx
  src/Components/main/info-modal.jsx
  src/Components/main/main.jsx
Labels: review-FE

#220 [team-31][FE] 아울 & 올리버 2주차 두 번째 PR
  frontend/sidedish/json-server/db.json
  frontend/sidedish/package.json
  frontend/sidedish/public/carouselMockData.json
  frontend/sidedish/src/components/itemCard/ItemCard.jsx
  frontend/sidedish/src/components/itemCard/ItemCards.jsx
  frontend/sidedish/src/components/loader/Loader.jsx
  frontend/sidedish/src/components/main/Main.jsx
  frontend/sidedish/src/components/popup/OrderDetail.jsx
  frontend/sidedish/src/components/popup/OrderNumber.jsx
  frontend/sidedish/src/components/popup/Popup.jsx
  frontend/sidedish/src/components/popup/PopupDetail.jsx
  frontend/sidedish/src/components/popup/PopupOrderContents.jsx
  frontend/sidedish/src/components/popup/RelatedContents.jsx
  frontend/sidedish/src/components/popup/RelatedLists.jsx
  frontend/sidedish/src/consts/constants.js
  frontend/sidedish/src/util/fetchData.js
  frontend/sidedish/yarn.lock
Labels: review-FE

#157 [team-34][FE][JS&Geon] 2주차 수요일 pr
  front/src/App.js
  front/src/GlobalStyles.js
  front/src/api.js
  front/src/components/Alert.js
  front/src/components/Badges.js
  front/src/components/Card.js
  front/src/components/CardSlider.js
  front/src/components/CategoryMenu.js
  front/src/components/Event.js
  front/src/components/Header.js
  front/src/components/Main.js
  front/src/components/Modal.js
  front/src/components/ProductDetail.js
  front/src/components/Promotion.js
  front/src/components/RelatedProduct.js
  front/src/images/left.png
  front/src/images/nextBlackBtn.svg
  front/src/images/prevBlackBtn.svg
  front/src/images/right.png
  front/src/theme.js
Labels: review-FE

#177 [team-8][FE] 베니 & 포키 2주차 두번째 PR
  README.md
  app/build/asset-manifest.json
  app/build/images/Arrow_black.svg
  app/build/images/Arrow_grey.svg
  app/build/images/Cart.svg
  app/build/images/Left.svg
  app/build/images/Minus.svg
  app/build/images/ModalCarouselLeft.svg
  app/build/images/ModalCarouselLeftDisable.svg
  app/build/images/ModalCarouselRight.svg
  app/build/images/ModalCarouselRightDisable.svg
  app/build/images/MyPage.svg
  app/build/images/Plus.svg
  app/build/images/Right.svg
  app/build/images/Search.svg
  app/build/index.html
  app/build/static/js/main.14dfbd1b.js
  app/build/static/js/main.14dfbd1b.js.LICENSE.txt
  app/build/static/js/main.14dfbd1b.js.map
  app/package.json
  app/public/images/Arrow_black.svg
  app/public/images/Arrow_grey.svg
  app/public/images/ModalCarouselLeftDisable.svg
  app/public/images/ModalCarouselRightDisable.svg
  app/public/index.html
  app/src/components/App.js
  app/src/components/App.jsx
  app/src/components/Card.js
  app/src/components/Card.jsx
  app/src/components/CardList.jsx
  app/src/components/Category.js
  app/src/components/Category.jsx
  app/src/components/Header.js
  app/src/components/Header.jsx
  app/src/components/MainCategories.jsx
  app/src/components/MainTab.js
  app/src/components/MainTab.jsx
  app/src/components/Modal/Alert.js
  app/src/components/Modal/Alert.jsx
  app/src/components/Modal/Carousel.js
  app/src/components/Modal/Carousel.jsx
  app/src/components/Modal/Modal.js
  app/src/components/Modal/Modal.jsx
  app/src/components/Modal/Product.js
  app/src/components/Modal/ProductDetailModal.jsx
  app/src/components/Slider.jsx
  app/src/components/Thumbnail.jsx
  app/src/index.js
  app/src/store/store.js
  app/src/styled-components/global.js
  app/src/styled-components/theme.js
  app/src/styled-components/utils.js
  app/src/styles/Modal/Carousel.js
  app/src/styles/Modal/Modal.js
Labels: review-FE
