Repository codesquad-members-2022/sidedish, pull requests merged in 2022-05, with the labels that each got.

#206 [Team-18] [Eddy & Kai] Collection View Header 버그 수정 등
  SideDishApp/.swiftlint.yml
  SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  SideDishApp/SideDishApp/Model/Entity/Money.swift
  SideDishApp/SideDishApp/Model/Networking/APIRequestable.swift
  SideDishApp/SideDishApp/Model/Networking/CategoryRequest.swift
  SideDishApp/SideDishApp/Model/Networking/ImageRequest.swift
  SideDishApp/SideDishApp/View/CollectionViewLayoutFactory.swift
  SideDishApp/SideDishApp/View/HeaderView.swift
  SideDishApp/SideDishApp/View/MainViewController.swift
  SideDishApp/SideDishApp/ViewModel/HeaderViewModel.swift
  SideDishApp/SideDishApp/ViewModel/MainCollectionViewModel.swift
  SideDishApp/SideDishApp/ViewModel/ProductDetailViewModel.swift
  SideDishApp/SideDishAppTests/APIRequestableTests.swift
  SideDishApp/SideDishAppTests/MainCollectionViewModelTests.swift
  SideDishApp/SideDishAppTests/ProductDetailViewModelTests.swift
Labels: review-iOS

#214 [team04][BE] 2주차 두번째 PR #4
  BE/build.gradle
  BE/src/main/java/kr/codesquad/sidedish/config/WebConfig.java
  BE/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
  BE/src/main/java/kr/codesquad/sidedish/controller/DishController.java
  BE/src/main/java/kr/codesquad/sidedish/controller/EventController.java
  BE/src/main/java/kr/codesquad/sidedish/controller/OAuthController.java
  BE/src/main/java/kr/codesquad/sidedish/controller/OrderController.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Dish.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Event.java
  BE/src/main/java/kr/codesquad/sidedish/domain/Image.java
  BE/src/main/java/kr/codesquad/sidedish/dto/CategorizedDishes.java
  BE/src/main/java/kr/codesquad/sidedish/dto/DishDetailResponse.java
  BE/src/main/java/kr/codesquad/sidedish/dto/DishRecommendation.java
  BE/src/main/java/kr/codesquad/sidedish/dto/DishSimpleResponse.java
  BE/src/main/java/kr/codesquad/sidedish/dto/ErrorResponse.java
  BE/src/main/java/kr/codesquad/sidedish/dto/EventResponse.java
  BE/src/main/java/kr/codesquad/sidedish/dto/OrderRequest.java
  BE/src/main/java/kr/codesquad/sidedish/exception/ErrorCode.java
  BE/src/main/java/kr/codesquad/sidedish/exception/ExceptionCatcher.java
  BE/src/main/java/kr/codesquad/sidedish/interceptor/OrderInterceptor.java
  BE/src/main/java/kr/codesquad/sidedish/repository/JdbcDishRepository.java
  BE/src/main/java/kr/codesquad/sidedish/service/CategoryService.java
  BE/src/main/java/kr/codesquad/sidedish/service/DishService.java
  BE/src/main/java/kr/codesquad/sidedish/service/EventService.java
  BE/src/main/java/kr/codesquad/sidedish/service/OAuthService.java
  BE/src/main/java/kr/codesquad/sidedish/service/OrderService.java
  BE/src/test/java/kr/codesquad/sidedish/service/CategoryServiceTest.java
Labels: review-BE

#215 [team-33 sonya&난정] 2주차 금요일 PR
  frontend/sidedish/.gitignore
  frontend/sidedish/package-lock.json
  frontend/sidedish/package.json
  frontend/sidedish/src/index.js
  frontend/sidedish/src/utils.js
  frontend/sidedish/src/view/App.jsx
  frontend/sidedish/src/view/GlobalStyle.jsx
  frontend/sidedish/src/view/Home.jsx
  frontend/sidedish/src/view/Login.jsx
  frontend/sidedish/src/view/header/Header.jsx
  frontend/sidedish/src/view/header/Header.style.js
  frontend/sidedish/src/view/sidedish/BigSidedish.jsx
  frontend/sidedish/src/view/sidedish/Button2ShowAllCategory.jsx
  frontend/sidedish/src/view/sidedish/Sidedish.style.js
  frontend/sidedish/src/view/sidedish/SidedishCards.jsx
  frontend/sidedish/src/view/sidedish/SmallSidedish.jsx
  frontend/sidedish/src/view/sidedish/card/Card.jsx
  frontend/sidedish/src/view/sidedish/card/Card.style.js
  frontend/sidedish/src/view/sidedish/carousel/Carousel.jsx
  frontend/sidedish/src/view/sidedish/carousel/Carousel.style.js
  frontend/sidedish/src/view/sidedish/popup/Popup.jsx
  frontend/sidedish/src/view/sidedish/popup/Popup.style.js
  frontend/sidedish/src/view/sidedish/recommendCarousel/Carousel.css
  frontend/sidedish/src/view/sidedish/recommendCarousel/recommendCarousel.jsx
  package-lock.json
Labels: review-FE

#174 [Team-5 BE 익조 & 피오] Sidedish 프로젝트 2주차(금요일) 코드 리뷰 요청
  BE/src/main/java/com/sidedish/config/MvcConfig.java
  BE/src/main/java/com/sidedish/controller/EventCategoryController.java
  BE/src/main/java/com/sidedish/controller/LoginController.java
  BE/src/main/java/com/sidedish/controller/MenuCategoryController.java
  BE/src/main/java/com/sidedish/controller/ResponseMessage.java
  BE/src/main/java/com/sidedish/controller/SideDishController.java
  BE/src/main/java/com/sidedish/controller/SideDishDetailsController.java
  BE/src/main/java/com/sidedish/controller/UserOrderController.java
  BE/src/main/java/com/sidedish/domain/SideDish.java
  BE/src/main/java/com/sidedish/domain/User.java
  BE/src/main/java/com/sidedish/domain/UserOrder.java
  BE/src/main/java/com/sidedish/dto/EventCategoryDto.java
  BE/src/main/java/com/sidedish/dto/EventCategoryListDto.java
  BE/src/main/java/com/sidedish/dto/MenuCategoryDto.java
  BE/src/main/java/com/sidedish/dto/MenuCategoryListDto.java
  BE/src/main/java/com/sidedish/dto/SideDishDetailsDto.java
  BE/src/main/java/com/sidedish/dto/SideDishDto.java
  BE/src/main/java/com/sidedish/dto/SideDishListDto.java
  BE/src/main/java/com/sidedish/dto/SideDishOrderDto.java
  BE/src/main/java/com/sidedish/mapper/SideDishMapper.java
  BE/src/main/java/com/sidedish/mapper/UserOrderMapper.java
  BE/src/main/java/com/sidedish/repository/MenuCategoryRepository.java
  BE/src/main/java/com/sidedish/repository/SideDishRepository.java
  BE/src/main/java/com/sidedish/repository/UserOrderRepository.java
  BE/src/main/java/com/sidedish/repository/UserRepository.java
  BE/src/main/java/com/sidedish/service/AccessToken.java
  BE/src/main/java/com/sidedish/service/EventCategoryService.java
  BE/src/main/java/com/sidedish/service/LoginService.java
  BE/src/main/java/com/sidedish/service/MenuCategoryService.java
  BE/src/main/java/com/sidedish/service/SideDishService.java
  BE/src/main/java/com/sidedish/service/UserOrderService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-BE

#182 [Team-5 FE BB & JinJeon] Sidedish 프로젝트 2주차(금요일) PR
  fe/package.json
  fe/public/index.html
  fe/src/Component/Card/Card.jsx
  fe/src/Component/Card/Card.styled.js
  fe/src/Component/Card/CardDiscountType.jsx
  fe/src/Component/Card/CardDiscountType.styled.js
  fe/src/Component/Card/CardImageAndFlag.jsx
  fe/src/Component/Card/CardPrice.jsx
  fe/src/Component/DetailPage/DetailInfoContext.jsx
  fe/src/Component/DetailPage/DetailPage.jsx
  fe/src/Component/DetailPage/DetailPage.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/CloseBtnArea/CloseBtnArea.jsx
  fe/src/Component/DetailPage/DetailPageDesc/CloseBtnArea/CloseBtnArea.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/DetailPageDesc.jsx
  fe/src/Component/DetailPage/DetailPageDesc/DetailPageDesc.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Explaination.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Explanation.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Images/Images.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Images/Images.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/Alert/Alert.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/Alert/Alert.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/Order.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/Order.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderInfo/Counter/Counter.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderInfo/Counter/Counter.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderInfo/DeliveryInfo/DeliveryInfo.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderInfo/DeliveryInfo/DeliveryInfo.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderInfo/OrderBtn/OrderBtn.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderInfo/OrderBtn/OrderBtn.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderInfo/OrderInfo.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderInfo/OrderInfo.styled.js
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderPrice/OrderPrice.jsx
  fe/src/Component/DetailPage/DetailPageDesc/Explaination/Order/OrderPrice/OrderPrice.styled.js
  fe/src/Component/Header/HeaderRight/HeaderRight.jsx
  fe/src/Component/Main/EventArea/EventTab/EventTab.styled.js
  fe/src/Component/Main/RestCategoriesArea/BtnShowAndHideArea.jsx
  fe/src/Component/Main/RestCategoriesArea/RestCategories/RestCategories.jsx
  fe/src/Component/Main/RestCategoriesArea/RestCategoriesArea.jsx
  fe/src/Component/Main/SideDishItemsArea/Category/Category.jsx
  fe/src/Component/Main/SideDishItemsArea/Category/ImgSlider/SliderButton.jsx
  fe/src/Component/Main/SideDishItemsArea/SideDishItemsArea.jsx
  fe/src/MockData/MockData.jsx
  fe/src/Portal/Portal.js
  fe/src/Service/eventCategoriesApi.js
  fe/src/Service/loginApi.js
  fe/src/Service/menuCategoriesApi.js
  fe/src/Service/orderApi.js
  fe/src/Service/sideDishesApi.js
  fe/src/Styles/Normalize.js
  fe/src/Util/util.js
  fe/src/common/constants.js
  fe/src/common/dataTools.js
  fe/src/index.jsx
Labels: review-FE

#205 [team-32][FE] otter & jinnie 2주차 두 번째 PR review-FE
  fe/src/App.js
  fe/src/component/Tab/Tab.js
  fe/src/component/UI/Card.js
  fe/src/component/UI/CardsWrapper.js
  fe/src/component/bottom/More.js
  fe/src/component/bottom/Slide.js
  fe/src/component/bottom/Slides.js
  fe/src/component/modal/DetailImage.js
  fe/src/component/modal/DetailInfo.js
  fe/src/component/modal/Modal.js
  fe/src/component/modal/ModalSlider.js
  fe/src/component/modal/ProductDetail.js
  fe/src/constants/constansts.js
  fe/src/store/store.js
  fe/src/utils/utils.js
Labels: review-FE

#175 [team-32][BE][선을로&헤이호] 5번째 PR 요청
  be/build.gradle
  be/src/main/java/kr/codesquad/sidedish/controller/ProductController.java
  be/src/main/java/kr/codesquad/sidedish/domain/DishType.java
  be/src/main/java/kr/codesquad/sidedish/domain/ShippingInfo.java
  be/src/main/java/kr/codesquad/sidedish/domain/SideDishType.java
  be/src/main/java/kr/codesquad/sidedish/handler/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/sidedish/repository/MemoryProductRepository.java
  be/src/main/java/kr/codesquad/sidedish/repository/ProvisionProductRepository.java
  be/src/main/java/kr/codesquad/sidedish/repository/ShippingInfoRepository.java
  be/src/main/java/kr/codesquad/sidedish/response/CommonCode.java
  be/src/main/java/kr/codesquad/sidedish/response/CommonResponse.java
  be/src/main/java/kr/codesquad/sidedish/service/ProductService.java
  be/src/main/java/kr/codesquad/sidedish/service/ShippingInfoDTO.java
  be/src/main/resources/application.properties
  be/src/main/resources/sql/data.sql
  be/src/main/resources/sql/schema.sql
  be/src/test/java/kr/codesquad/sidedish/domain/DishTypeTest.java
  be/src/test/java/kr/codesquad/sidedish/domain/SideDishTypeTestType.java
  be/src/test/java/kr/codesquad/sidedish/repository/ProductRepositoryTest.java
  be/src/test/java/kr/codesquad/sidedish/service/ProductServiceTest.java
Labels: review-BE

#192 [BE][[team-33] Miller, Nathan - OAuth 와 JWT 를 이용한 로그인 구현
  README.md
  backend/.gitignore
  backend/build.gradle
  backend/deploy/back_deploy.sh
  backend/deploy/nginx.conf
  backend/src/main/java/com/codesquad/sidedish/auth/AuthService.java
  backend/src/main/java/com/codesquad/sidedish/auth/JwtFactory.java
  backend/src/main/java/com/codesquad/sidedish/auth/LoginFilter.java
  backend/src/main/java/com/codesquad/sidedish/auth/client/AuthClient.java
  backend/src/main/java/com/codesquad/sidedish/auth/client/GithubAuthClient.java
  backend/src/main/java/com/codesquad/sidedish/auth/controller/AbstractAuthController.java
  backend/src/main/java/com/codesquad/sidedish/auth/controller/AuthController.java
  backend/src/main/java/com/codesquad/sidedish/auth/controller/GithubAuthController.java
  backend/src/main/java/com/codesquad/sidedish/auth/domain/GithubToken.java
  backend/src/main/java/com/codesquad/sidedish/auth/domain/GithubUser.java
  backend/src/main/java/com/codesquad/sidedish/auth/domain/OAuthProperties.java
  backend/src/main/java/com/codesquad/sidedish/auth/domain/OAuthProvider.java
  backend/src/main/java/com/codesquad/sidedish/config/OAuthConfig.java
  backend/src/main/java/com/codesquad/sidedish/dish/DishService.java
  backend/src/main/java/com/codesquad/sidedish/dish/domain/Dish.java
  backend/src/main/java/com/codesquad/sidedish/dish/dto/DishListResponse.java
  backend/src/main/java/com/codesquad/sidedish/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/codesquad/sidedish/exception/GoneException.java
  backend/src/main/java/com/codesquad/sidedish/exception/unchecked/BusinessException.java
  backend/src/main/java/com/codesquad/sidedish/exception/unchecked/NotFoundException.java
  backend/src/main/java/com/codesquad/sidedish/exception/unchecked/OutOfStockException.java
  backend/src/main/java/com/codesquad/sidedish/order/OrderService.java
  backend/src/main/java/com/codesquad/sidedish/order/domain/User.java
  backend/src/main/java/com/codesquad/sidedish/other/DeliveryPolicy.java
  backend/src/main/java/com/codesquad/sidedish/other/DiscountPolicy.java
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/schema.sql
  backend/src/test/java/com/codesquad/sidedish/CategoryRepositoryTest.java
  backend/src/test/java/com/codesquad/sidedish/DishRepositoryTest.java
  backend/src/test/java/com/codesquad/sidedish/JwtTest.java
Labels: review-BE

#198 [team-01][FE] 제품 상세보기 Modal 구현, 리팩토링
  FE/db.json
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.js
  FE/src/OAuth/Login.jsx
  FE/src/assets/minus.svg
  FE/src/assets/plus.svg
  FE/src/components/Card/Badge.jsx
  FE/src/components/Card/Badge.style.js
  FE/src/components/Card/Card.jsx
  FE/src/components/Card/Card.style.js
  FE/src/components/Card/Thumbnail.jsx
  FE/src/components/Card/Thumbnail.style.js
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/Header.style.js
  FE/src/components/Main/Main.style.js
  FE/src/components/Modal/Modal.jsx
  FE/src/components/Modal/Modal.style.js
  FE/src/components/Modal/OrderAlertModal.jsx
  FE/src/components/Modal/OrderAlertModal.style.js
  FE/src/components/Modal/Portal.jsx
  FE/src/components/Slider/Slider.jsx
  FE/src/components/Slider/Slider.style.js
  FE/src/components/Special/Special.jsx
  FE/src/constants/api.js
  FE/src/constants/productInfo.js
  FE/src/constants/sliderSpec.js
  FE/src/data/categoryTitle.js
  FE/src/data/specialTab.js
  FE/src/pages/Callback.jsx
  FE/src/pages/Home.jsx
Labels: review-FE

#186 [team-26] [Android] SideDish Project PR 4 - 피드백 적용 / 깃허브 로그인 연동 / 네트워크 에러 시 화면 처리 / 메뉴 이미지 로딩중, 실패 시 처리
  Android/app/build.gradle
  Android/app/src/main/java/com/codesquadhan/sidedish/data/model/be/MainResponseItem.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/data/repository/DetailRepository.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/di/NetworkModule.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/network/DetailService.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/network/MenuService.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/common/Common.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/common/ImageLoadingFailListener.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/common/NetworkErrorBindingAdapter.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/common/TextBindingAdapters.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/common/extensionfunction/addAllAndSetIsWhite.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/detail/DetailActivity.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/detail/DetailAdapter.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/detail/DetailViewModel.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/detail/ViewPagerAdapter.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/main/MainActivity.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/main/MainAdapter.kt
  Android/app/src/main/java/com/codesquadhan/sidedish/ui/main/MainViewModel.kt
  Android/app/src/main/res/drawable/load_fail.png
  Android/app/src/main/res/drawable/loading_icon.gif
  Android/app/src/main/res/layout/activity_detail.xml
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/layout/item_detail.xml
  Android/app/src/main/res/layout/item_main_food.xml
  Android/app/src/main/res/layout/item_main_header.xml
  Android/app/src/main/res/layout/item_viewpager_image.xml
  Android/app/src/main/res/values/strings.xml
Labels: review-android

#179 [Team-29][Android] 피드백 적용 및 로그인, 주문 서비스 구현
  .gitignore
  app/build.gradle
  app/src/main/java/com/example/sideDish/MainActivity.kt
  app/src/main/java/com/example/sideDish/SideDishApplication.kt
  app/src/main/java/com/example/sideDish/data/model/FoodDetail.kt
  app/src/main/java/com/example/sideDish/data/source/DetailRemoteRepository.kt
  app/src/main/java/com/example/sideDish/data/source/DetailRepository.kt
  app/src/main/java/com/example/sideDish/data/source/FoodRemoteRepository.kt
  app/src/main/java/com/example/sideDish/data/source/FoodRepository.kt
  app/src/main/java/com/example/sideDish/data/source/OrderRepository.kt
  app/src/main/java/com/example/sideDish/di/NetworkModule.kt
  app/src/main/java/com/example/sideDish/di/RepositoryModule.kt
  app/src/main/java/com/example/sideDish/network/OrderRetrofitService.kt
  app/src/main/java/com/example/sideDish/network/dto/DetailDto.kt
  app/src/main/java/com/example/sideDish/network/dto/OrderDto.kt
  app/src/main/java/com/example/sideDish/network/dto/SideDishDto.kt
  app/src/main/java/com/example/sideDish/ui/BindingAdapters.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListAdapter.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListFragment.kt
  app/src/main/java/com/example/sideDish/ui/foodlist/FoodListViewModel.kt
  app/src/main/java/com/example/sideDish/ui/login/LoginFragment.kt
  app/src/main/java/com/example/sideDish/ui/productdetail/FoodDetailViewModel.kt
  app/src/main/java/com/example/sideDish/ui/productdetail/ProductDetailFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/main_summary_item.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-android

#181 [Team30] [Android] - 피드백 반영, 이미지 캐시 처리
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/todo/sidedish/common/Constants.kt
  app/src/main/java/com/example/todo/sidedish/common/LruMemoryCache.kt
  app/src/main/java/com/example/todo/sidedish/data/remote/OnBanApi.kt
  app/src/main/java/com/example/todo/sidedish/data/repository/MenuRepositoryImpl.kt
  app/src/main/java/com/example/todo/sidedish/domain/Repository.kt
  app/src/main/java/com/example/todo/sidedish/ui/common/TextBindingAdapters.kt
  app/src/main/java/com/example/todo/sidedish/ui/login/LoginFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuAdapter.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menu/MenuViewModel.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/MenuDetailFragment.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/MenuDetailViewModel.kt
  app/src/main/java/com/example/todo/sidedish/ui/menudetail/OrderCompleteDialogFragment.kt
  app/src/main/res/layout/fragment_menu_detail.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: review-android

#218 [team28 - Backend] OAuth 구현 및 자동배포 구현, Mysql 적용
  backend/build.gradle
  backend/deploy/deploy.sh
  backend/src/main/java/com/team28/sidedish/config/WebConfig.java
  backend/src/main/java/com/team28/sidedish/controller/CategoryController.java
  backend/src/main/java/com/team28/sidedish/controller/OAuthController.java
  backend/src/main/java/com/team28/sidedish/controller/dto/OAuthLoginResponse.java
  backend/src/main/java/com/team28/sidedish/controller/oauth/OAuthAccessTokenRequest.java
  backend/src/main/java/com/team28/sidedish/controller/oauth/OAuthAccessTokenResponse.java
  backend/src/main/java/com/team28/sidedish/controller/oauth/OAuthUrl.java
  backend/src/main/java/com/team28/sidedish/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/team28/sidedish/exception/LoginFailedException.java
  backend/src/main/java/com/team28/sidedish/exception/URISyntaxException.java
  backend/src/main/java/com/team28/sidedish/interceptor/TokenVerifyInterceptor.java
  backend/src/main/java/com/team28/sidedish/repository/entity/OrderProductsEntity.java
  backend/src/main/java/com/team28/sidedish/service/GithubApiService.java
  backend/src/main/java/com/team28/sidedish/service/MockCategoryService.java
  backend/src/main/java/com/team28/sidedish/service/MockOrderService.java
  backend/src/main/java/com/team28/sidedish/service/MockProductDetailService.java
  backend/src/main/java/com/team28/sidedish/service/MockProductImageService.java
  backend/src/main/java/com/team28/sidedish/service/MockProductService.java
  backend/src/main/java/com/team28/sidedish/service/OAuthService.java
  backend/src/main/java/com/team28/sidedish/service/dto/UserProfile.java
  backend/src/main/java/com/team28/sidedish/utils/EnvUtils.java
  backend/src/main/java/com/team28/sidedish/utils/JwtUtils.java
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/schema.sql
Labels: review-BE

#190 [Team-31 BE 노리 & 휘] Side-dish 프로젝트 2주차(금요일) 코드 리뷰 요청
  backend/src/main/java/team31/codesuqad/sidedish/controller/CategoryController.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/DishController.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/EventController.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/AllCategoriesResponse.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/CategoryNames.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/CategoryResponse.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/DetailedDishDto.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/DiscountDto.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/DishDto.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/EventTabDto.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/EventTabListDto.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/EventTabResponse.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/ImageDto.java
  backend/src/main/java/team31/codesuqad/sidedish/controller/dto/RecommendDto.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/Category.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/Delivery.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/Discount.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/DiscountPolicy.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/Dish.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/Dishes.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/Event.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/EventTabs.java
  backend/src/main/java/team31/codesuqad/sidedish/domain/Image.java
  backend/src/main/java/team31/codesuqad/sidedish/repository/DeliveryRepository.java
  backend/src/main/java/team31/codesuqad/sidedish/repository/DiscountPoliciesRepository.java
  backend/src/main/java/team31/codesuqad/sidedish/repository/DiscountPolicyRepository.java
  backend/src/main/java/team31/codesuqad/sidedish/repository/DishRepository.java
  backend/src/main/java/team31/codesuqad/sidedish/repository/DishesRepository.java
  backend/src/main/java/team31/codesuqad/sidedish/repository/EventTabRepository.java
  backend/src/main/java/team31/codesuqad/sidedish/repository/EventTabsRepository.java
  backend/src/main/java/team31/codesuqad/sidedish/service/CategoryService.java
  backend/src/main/java/team31/codesuqad/sidedish/service/DeliveryService.java
  backend/src/main/java/team31/codesuqad/sidedish/service/DiscountPoliciesService.java
  backend/src/main/java/team31/codesuqad/sidedish/service/DiscountPolicyService.java
  backend/src/main/java/team31/codesuqad/sidedish/service/DishService.java
  backend/src/main/java/team31/codesuqad/sidedish/service/DishesService.java
  backend/src/main/java/team31/codesuqad/sidedish/service/EventService.java
  backend/src/main/java/team31/codesuqad/sidedish/type/EventType.java
  backend/src/main/java/team31/codesuqad/sidedish/type/ImageType.java
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/schema.sql
Labels: review-BE

#211 [team-10][FE][이든, Khan] 반찬가게 Step4
  package-lock.json
  package.json
  public/data/mainDish.json
  public/data/sideDish.json
  public/index.html
  src/App.js
  src/Header.js
  src/MainCard.js
  src/SubCard.js
  src/components/Card.js
  src/components/CardBox.js
  src/components/CardOrderPage.js
  src/components/CategoryTitle.js
  src/components/Infos.js
  src/components/Modal.js
  src/components/ModalInfo.js
  src/components/Order.js
  src/components/ShoppingInfo.js
  src/components/Slider.js
  src/components/Tab.js
  src/container/CardContainer.js
  src/css/mixins.js
  src/css/variables.js
Labels: review-FE

#201 [team-01][BE] 2주차 PR #2 #145
  BE/src/main/java/com/example/be/business/category/controller/CategoryController.java
  BE/src/main/java/com/example/be/business/category/controller/dto/PlanningDataResponse.java
  BE/src/main/java/com/example/be/business/category/repository/CategoryRepository.java
  BE/src/main/java/com/example/be/business/category/service/CategoryService.java
  BE/src/main/java/com/example/be/business/dish/controller/dto/DishSaveRequest.java
  BE/src/main/java/com/example/be/business/dish/controller/dto/PlanningDataResponse.java
  BE/src/main/java/com/example/be/business/dish/domain/DeliveryPriceOption.java
  BE/src/main/java/com/example/be/business/dish/domain/Dish.java
  BE/src/main/java/com/example/be/business/dish/repository/DishRepository.java
  BE/src/main/java/com/example/be/business/dish/service/CategoryType.java
  BE/src/main/java/com/example/be/business/dish/service/DishInformationResponse.java
  BE/src/main/java/com/example/be/business/dish/service/DishService.java
  BE/src/main/java/com/example/be/business/dish/service/InMemogryDatabase.java
  BE/src/main/java/com/example/be/business/dish/service/InMemoryDatabase.java
  BE/src/main/java/com/example/be/business/event/DishListener.java
  BE/src/main/java/com/example/be/business/event/dish/DishUpdatePublishEvent.java
  BE/src/main/java/com/example/be/common/exception/ExceptionHandler.java
  BE/src/main/java/com/example/be/common/login/token/TokenUtils.java
  BE/src/main/java/com/example/be/common/login/token/configuration/ClientRegistration.java
  BE/src/main/java/com/example/be/common/login/token/configuration/OauthClientProperties.java
  BE/src/main/java/com/example/be/common/login/token/github/GithubTokenUtils.java
  BE/src/main/java/com/example/be/common/login/token/jwt/Header.java
  BE/src/main/java/com/example/be/common/login/token/jwt/JwtToken.java
Labels: review-BE

#191 [Team-27] [Android] OAuth 구현 및 리뷰 사항 적용
  android/app/src/main/java/com/example/sidedish/data/Menu.kt
  android/app/src/main/java/com/example/sidedish/data/OrderMenu.kt
  android/app/src/main/java/com/example/sidedish/data/datasource/DataSource.kt
  android/app/src/main/java/com/example/sidedish/data/datasource/MenuListDataSource.kt
  android/app/src/main/java/com/example/sidedish/data/dto/MenuDetailDTO.kt
  android/app/src/main/java/com/example/sidedish/data/repository/MenuListRepository.kt
  android/app/src/main/java/com/example/sidedish/network/ApiClient.kt
  android/app/src/main/java/com/example/sidedish/ui/adapter/MenuPageAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/detail/MenuDetailFragment.kt
  android/app/src/main/java/com/example/sidedish/ui/detail/MenuDetailTextAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/detail/OrderDialog.kt
  android/app/src/main/java/com/example/sidedish/ui/menu/HomeActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/viewmodel/MenuListViewModel.kt
  android/app/src/main/res/layout/fragment_detail.xml
  android/app/src/main/res/layout/item_menu_list.xml
Labels: review-android

#212 [Android] Hilt 적용 및 CoroutineExceptionHandler 적용, UI 보완
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/sidedish/MainApplication.kt
  android/app/src/main/java/com/example/sidedish/model/CEHModel.kt
  android/app/src/main/java/com/example/sidedish/model/PostRequest.kt
  android/app/src/main/java/com/example/sidedish/network/ApiService.kt
  android/app/src/main/java/com/example/sidedish/network/RetrofitAPI.kt
  android/app/src/main/java/com/example/sidedish/repository/MainRemoteDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/MainRepository.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductCountRemoteDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductCountRemoteDataSourceImpl.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductDetailDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductDetailRemoteDataSource.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductDetailRemoteDataSourceImpl.kt
  android/app/src/main/java/com/example/sidedish/repository/ProductDetailRepository.kt
  android/app/src/main/java/com/example/sidedish/repository/module/MainModule.kt
  android/app/src/main/java/com/example/sidedish/repository/module/ProductCountModule.kt
  android/app/src/main/java/com/example/sidedish/repository/module/ProductDetailModule.kt
  android/app/src/main/java/com/example/sidedish/ui/MainActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/MainHomeAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/MainViewModel.kt
  android/app/src/main/java/com/example/sidedish/ui/ProductDetailActivity.kt
  android/app/src/main/java/com/example/sidedish/ui/ProductDetailViewModel.kt
  android/app/src/main/java/com/example/sidedish/ui/common/BindingAdapter.kt
  android/app/src/main/java/com/example/sidedish/ui/common/ThrowableState.kt
  android/app/src/main/java/com/example/sidedish/ui/common/ViewModelFactory.kt
  android/app/src/main/res/layout/activity_product_detail.xml
  android/app/src/main/res/layout/item_menu_data.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: review-android

#213 [team07][FE][Ver&S] 2주차 금요일 PR
  FE/build/index.html
  FE/build/main.js
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.js
  FE/src/Portal.js
  FE/src/assets/image/close.svg
  FE/src/assets/image/deliveryType1.svg
  FE/src/assets/image/deliveryType2.svg
  FE/src/assets/image/deliveryType3.svg
  FE/src/assets/image/leftButton.svg
  FE/src/assets/image/minus.svg
  FE/src/assets/image/order.svg
  FE/src/assets/image/plus.svg
  FE/src/assets/image/rightButton.svg
  FE/src/best.json
  FE/src/category.json
  FE/src/components/atoms/Button/CategoryButtonLeft.jsx
  FE/src/components/atoms/Button/CategoryButtonLeft.scss
  FE/src/components/atoms/Button/CategoryButtonRight.jsx
  FE/src/components/atoms/Button/CategoryButtonRight.scss
  FE/src/components/atoms/Figure/ArticleFigure.jsx
  FE/src/components/atoms/Figure/ArticleFigure.scss
  FE/src/components/atoms/Figure/FigureWithSize.jsx
  FE/src/components/atoms/Label/DeliveryLabel.jsx
  FE/src/components/atoms/Label/DeliveryLabel.scss
  FE/src/components/atoms/Label/MenuLabel.scss
  FE/src/components/atoms/ModalBackground/ModalBackground.jsx
  FE/src/components/atoms/P/CategoryTitle.jsx
  FE/src/components/atoms/P/CategoryTitle.scss
  FE/src/components/molecules/Description/MenuDescription.jsx
  FE/src/components/molecules/Description/MenuDescription.scss
  FE/src/components/molecules/Icons/Icons.styled.js
  FE/src/components/molecules/MainCategoryNav/MainCategoryNav.jsx
  FE/src/components/molecules/MainSubCatgoryNav/MainSubCategoryNav.jsx
  FE/src/components/molecules/MenuPrices/MenuPrices.jsx
  FE/src/components/organisms/Article/MenuArticle.jsx
  FE/src/components/organisms/Article/MenuArticle.scss
  FE/src/components/organisms/CategoryContents/CategoryContents.jsx
  FE/src/components/organisms/CategorySlideSection/CategorySlideSection.jsx
  FE/src/components/organisms/CategorySlideSection/CategorySlideSection.scss
  FE/src/components/organisms/MenuDetailSection/MenuDetailSection.jsx
  FE/src/components/organisms/MenuDetailSection/MenuDetailSection.scss
  FE/src/components/organisms/MenuSection/MenuSection.jsx
  FE/src/components/organisms/ModalContents/ModalContents.jsx
  FE/src/components/organisms/ModalContents/ModalContents.scss
  FE/src/components/templates/Category/CategorySection.jsx
  FE/src/components/templates/Category/CategorySection.scss
  FE/src/components/templates/Modal/Modal.jsx
  FE/src/components/templates/Modal/Modal.scss
  FE/src/components/templates/Promotion/Promotion.jsx
  FE/src/constant/constant.js
Labels: review-FE

#189 [Team-02][FE] 2주차 두 번째 PR
  frontend/public/icon/minus-icon.svg
  frontend/public/icon/plus-icon.svg
  frontend/public/icon/prevButton-icon.svg
  frontend/src/App.js
  frontend/src/components/Category/Category.jsx
  frontend/src/components/GoodsBlock/GoodsBlock.css
  frontend/src/components/GoodsBlock/GoodsBlock.jsx
  frontend/src/components/Modal/Modal.jsx
  frontend/src/components/Modal/Modal.styled.jsx
  frontend/src/components/SideDishContentsList/SideDishContentsList.jsx
  frontend/src/components/Slider/Slider.jsx
  frontend/src/components/Slider/Slider.styled.jsx
  frontend/src/components/index.js
  frontend/src/constants/constants.js
  frontend/src/constants/iconPath.js
  frontend/src/constants/index.js
  frontend/src/constants/urlPath.js
  frontend/src/containers/SideDishContents/SideDishContents.jsx
  frontend/src/containers/SideDishContents/SideDishContents.styled.jsx
  frontend/src/containers/SpecialPromotion/SpecialPromotion.jsx
  frontend/src/data/goods.json
  frontend/src/utils/index.js
  frontend/src/utils/utils.js
Labels: review-FE

#171 [team-02][BE][Phill & Hanse] sidedish 2주차 PR#3
  backend/build.gradle
  backend/src/main/java/com/sidedish/SidedishApplication.java
  backend/src/main/java/com/sidedish/domain/Image.java
  backend/src/main/java/com/sidedish/domain/product/EventBadge.java
  backend/src/main/java/com/sidedish/domain/product/EventCategory.java
  backend/src/main/java/com/sidedish/domain/product/MainCategory.java
  backend/src/main/java/com/sidedish/domain/product/Order.java
  backend/src/main/java/com/sidedish/domain/product/OrderProduct.java
  backend/src/main/java/com/sidedish/domain/product/Product.java
  backend/src/main/java/com/sidedish/domain/product/ProductOrder.java
  backend/src/main/java/com/sidedish/domain/user/Address.java
  backend/src/main/java/com/sidedish/domain/user/Member.java
  backend/src/main/java/com/sidedish/domain/user/User.java
  backend/src/main/java/com/sidedish/repository/MemberRepository.java
  backend/src/main/java/com/sidedish/repository/OrderProductRepository.java
  backend/src/main/java/com/sidedish/repository/OrderRepository.java
  backend/src/main/java/com/sidedish/repository/ProductRepository.java
  backend/src/main/java/com/sidedish/servcie/ProductService.java
  backend/src/main/java/com/sidedish/web/controller/ProductController.java
  backend/src/main/java/com/sidedish/web/dto/CategoryProductDto.java
  backend/src/main/java/com/sidedish/web/dto/ImageDto.java
  backend/src/main/java/com/sidedish/web/dto/MainCategoryProductDto.java
  backend/src/main/java/com/sidedish/web/dto/OrderDto.java
  backend/src/main/java/com/sidedish/web/dto/ProductDetailDto.java
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/main/resources/templates/index.html
  backend/src/test/java/com/sidedish/SidedishApplicationTests.java
Labels: review-BE
